### ISSUE TITLE
straight direct bare import on a single line

### ISSUE THREAD

**Issue by eskhool** [PyCQA/isort#1025]
I searched a lot but couldn't find any other issue that relates to this. Currently all straight imports are put on their own line

import os
import system
....

We prefer
import os, system

Isn't there any configuration for the same?

**Comment by eskhool** [comment]
I have implemented an optional flag combine_straight with a default value of false. Happy to raise a merge request if other people are interested.

**Comment by ssokolow** [comment]
I'm also interested.

In fact, I'm about to uninstall `isort` because I'm not willing to compromise on that point.

**Comment by eskhool** [comment]
Well you're in luck if that's your only issue with isort (I got this working quite well)
Will fork isort if I don't get a reply to this soon enough ...just don't like it when awesome projects get forked due to lack of code reviews :p

**Comment by timothycrosley** [comment]
@eskhool,

I will absolutely merge such a pull request! I'm in the middle of a refactor and have been pretty focused on it - to increase the maintainability of isort and my ability to keep up with issues as they appear. After all isort is not a full time job for me! And, not even close to the only Open Source project I maintain.  However, I try to quickly merge viable pull requests, and I'm always interested in bringing on additional maintainers or core developers where there is interest. Join maintainers do even get deploy to PYPI access.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
@eskhool Any update on this, I'd still love to get your improvement merged if you have it available. Even if it's in a form of the old prerefactor isort code base I'd be more than happy to help translate it to the new code base. Also, what other issues have you encountered?

**Comment by anirudnits** [comment]
@timothycrosley @eskhool is this active? otherwise I believe its a pertinent feature and I could work on this and open a PR.

**Comment by timothycrosley** [comment]
@anirudnits I say go for it! I haven't heard from @eskhool since November of last year so I think it's safe for the work to be taking up by another contributor.

Thanks!

~Timothy

**Comment by anirudnits** [comment]
Closing this as https://github.com/PyCQA/isort/pull/1554 has been merged into develop.
