### ISSUE TITLE
verbose-on-failure

### ISSUE THREAD

**Issue by omry** [PyCQA/isort#1115]
When debugging isort issues, it would be useful to allow verbose output only to files that were modified.
this is especially useful for more easily figuring up issues that are only showing up in CI.

I am am proposing a new flag which will enable this Behavior.

**Comment by anirudnits** [comment]
if nobody is working on this, I can take it up.

**Comment by timothycrosley** [comment]
Thanks @anirudnits! I've assigned it to you :)

**Comment by anirudnits** [comment]
Opened a PR  https://github.com/PyCQA/isort/pull/1517. Have a look! :)

**Comment by timothycrosley** [comment]
Closing this as @anirudnits PR has been merged (Thank you!) this will be in isort's October release (5.6.0)

Thanks!

~Timothy

**Comment by omry** [comment]
just to clarify, I am not sure if this is doing what the original was for (sorry if I was not clear enough):

In CI, I normally do not run in verbose because I want to minimize printed output.
Furthermore, I also run isort with --check --diff to allow me to more easily see what need to change.
The feature request was to support automatically enabling verbose printout (which provides the classification of what each import line is classified as) "retroactively" for files that failed the check.
This could be implemented by re-running isort for the failed files with --verbose if the flag is set (or maybe using some other means).

I will need to experiment with what was implemented, but judging by the code alone , I am not sure it's actually covering the feature request. (this it not to say that what was implemented is not useful).

**Comment by anirudnits** [comment]
@omry I believe the exact output you are referring to in the comments can be implemented with `isort . --check --diff --verbose --only-modified`. In this case, the verbose output will only be for the modified files, i.e those files which will fail in `check` phase. Does this cover your exact usage?

**Comment by omry** [comment]
Sounds like it does, I will give it a try once this is released.
Thanks!

**Comment by omry** [comment]
One thing that gave me pause was if a file is considered modified in --check mode, where it's not really modified.

**Comment by anirudnits** [comment]
@omry Yeah a file will be considered as being _modified_, if isort finds any changes to be made regardless if these changes are actually reflected in the file or not. I've added a specific test for this behavior.
