### ISSUE TITLE
Allow 2 spaces after an import block

### ISSUE THREAD

**Issue by dwaynebailey** [PyCQA/isort#119]
While PEP8 is unclear about how many lines after the import block it does say this:
"Separate top-level function and class definitions with two blank lines."

So in our code we add two lines after imports to closely match our high level double line breaks.

This probably isn't what other people do so being able to set the blank line following an import block would be a good option

**Comment by excitoon** [comment]
@timothycrosley `lines_after_import=2` does not help in all cases unfortunately:

```python3
if sys.version > (3, 8):
  import xxx

  class Abc:
    ...
```

In this example, I would like to have `lai=1` for non-top-level imports. 🤷‍♂️🤷‍♂️🤷‍♂️
