### ISSUE TITLE
as imports removed when `--combine-star` is set

### ISSUE THREAD

**Issue by timothycrosley** [PyCQA/isort#1380]
Currently, as imports will be removed, if a star import is present from the same module and `--combine-star` is enabled. This will likely break code that depends on the import aliasing.

**Comment by jack1142** [comment]
@timothycrosley should this be closed after #1376 got merged (and 5.4.0 released)?

**Comment by timothycrosley** [comment]
@jack1142 Thanks for the note! I've updated the changelog to point to the correct issue.

~Timothy
