### ISSUE TITLE
--float-to-top has no effect if no import is already at the top

### ISSUE THREAD

**Issue by pmeier** [PyCQA/isort#1382]
Consider the following snippet:

```python
def foo():
    pass

import a

def bar():
    pass
```

If you run `isort --float-to-top` nothing is changed. If you insert `import b` above the definition of `foo`, the same command correctly results in 

```python
import a
import b


def foo():
    pass


def bar():
    pass
```

**Comment by sztamas** [comment]
@timothycrosley I had a look at this.

Currently the `--float-to-top` is achieved by [this upfront parse and sort](https://github.com/PyCQA/isort/blob/develop/isort/core.py#L70-L107) that rearranges the input lines and floats up the imports to the top.
However this works only if there are any imports at the top to start with.

I think that when `config.float_to_top` is `True`, `import_index` returned by parse could be modified to return an index at the top of the file.

However, the top of the file probably shouldn't be `0`, we should skip over any docstrings and comments?

From PEP8:

> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants. 


What do you think?

Thanks,

Tamas

**Comment by timothycrosley** [comment]
That's right! And indeed back before isort supported multiple sections, it did do exactly this - so there may be some prior work to pull from

**Comment by timothycrosley** [comment]
A fix for this issue has just been deployed to PyPI in version 5.5.0 of isort.

Thanks!

~Timothy
