### ISSUE TITLE
Discrepancies on running isort in local vs Github Action

### ISSUE THREAD

**Issue by onlinejudge95** [PyCQA/isort#1384]
In reference to the following [build](https://github.com/onlinejudge95/rinnegan/pull/125/checks?check_run_id=983857077), the issue I am facing with isort is that when run locally using the same config a different behaviour is shown as compared to when run on a Github Action context. Given that I have pinned the dependency and using the same version in both settings I am unable to figure out what is leading to a different result. Here is the screenshot of a local run.
![isort](https://user-images.githubusercontent.com/44158581/90225098-6013e580-de2e-11ea-8491-baae34e071f9.png)

**Comment by onlinejudge95** [comment]
Apparently cd'ing into the directory did work. Still not sure why though :confused:

**Comment by timothycrosley** [comment]
Hi @onlinejudge95,

Sorry this behaviour caused confusion! isort, like many CLI tools, uses the current working directory as an input to determine the project location. If you want to make sure the behaviour is explicit you can pass in a [--settings-path](https://timothycrosley.github.io/isort/docs/configuration/options/#settings-path) or change the directory before running the command.

I'm glad you resolved your issue, and I hope the additional information is helpful!

~Timothy

**Comment by onlinejudge95** [comment]
I think it would be better to document this feature if not done yet.

**Comment by timothycrosley** [comment]
Agreed! This is something I've been meaning to document better as it's a pretty central interaction. I'm going to reopen this issue, just to make sure it doesn't fall off the radar as a documentation task.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This interaction has now been clarified in the documentation here: This interaction is now documented here: https://pycqa.github.io/isort/docs/configuration/config_files/
