### ISSUE TITLE
isort always skips __init__.py files

### ISSUE THREAD

**Issue by wolkenarchitekt** [PyCQA/isort#139]
I want to sort imports in my `__init__.py` files, too.
In settings, `__init__.py` is configured to be skipped as default:(https://github.com/timothycrosley/isort/blob/develop/isort/settings.py#L45)
When defining a custom settings file like this:

```
[settings]
line_length=100
skip=foobar.py
```

isort still skips `__init__.py` files in addition to skips defined by myself. I cannot turn of skipping these, only by changing settings.py of isort itself.

Either `__init__.py` should be removed from default skip settings, or its default value should be ignored if configfile contains a skip section, too.

**Comment by manoadamro** [comment]
did this ever get fixed? in 2019 this is still a problem

**Comment by jdufresne** [comment]
@manoadamro You can add the line `not_skip = __init__.py` to process `__init__.py`. Here is an example:

https://github.com/django/django/blob/master/setup.cfg#L17

**Comment by samuelcolvin** [comment]
This was fixed properly in **`v4.3.5`**.

`not_skip = __init__.py` is no longer required.

**Comment by emonette123** [comment]
For those of you still using an older version of isort (Murphy's law dictates I currently have to use v4.3.4!), the not_skip trick will only work if you do not have the recursive switch on. I do not know well that code, but it is using two completely different paths to check if a file should be skipped depending if that flag is on or off. If the recursive path flag is on, the config file is read, then the dictionary is update with the arguments. If you do not specify any skip argument, it looks like the default value of __init__.py makes its way back to the config... The workaround I found is to specify to skip an empty string, or just a space char: isort -s " ".
