### ISSUE TITLE
isort: off not working

### ISSUE THREAD

**Issue by chdsbd** [PyCQA/isort#1398]
I was having trouble getting the `isort: off` comment to work. I was able to get it to work in another file, but not in this example.

```python
# isort: off
from app.resources import (
    db,
    cache
)
# isort: on
```

.isort.cfg
```
[settings]
profile=black

```

`./.venv/bin/isort main.py --diff` output
```diff
--- /Users/chris/projects/isort-reproduction/main.py:before	2020-08-21 12:12:04.127048
+++ /Users/chris/projects/isort-reproduction/main.py:after	2020-08-21 12:14:49.983382
@@ -1,6 +1,4 @@
 # isort: off
-from app.resources import (
-    db,
-    cache
-)
+from app.resources import cache, db
+
 # isort: on
```

example repository: https://github.com/chdsbd/isort-reproduction

---
EDIT: strangely if I add two `#` to the top of the file this issue disappears:

```
#
#

# isort: off
from app.resources import (
    db,
    cache
)
# isort: on
```

**Comment by timothycrosley** [comment]
This change has just been deployed to PyPI in version 5.5.0

Thanks!

~Timothy
