### ISSUE TITLE
Add coloring to --diff output

### ISSUE THREAD

**Issue by GergelyKalmar** [PyCQA/isort#1405]
Although I was very excited to try out the color output config option (now that pylint allows isort >= 5), it does not seem to do all that much at the moment. In particular, I have expected that diffs will be nicely colored just like they are with git diff, but that does not seem to be the case. Am I missing something or is this not implemented yet?

Thank you!

**Comment by timothycrosley** [comment]
You are right, it is very limited in scope at the moment! Hopefully overtime it will become more comprehensive. For now, we will prioritize adding the color output to diffs.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This is now implemented in develop (thanks @sztamas!) and will make it's way out in the 5.5.0 release of isort which is slated for release by September 1st.

**Comment by GergelyKalmar** [comment]
Amazing, thank you both very much!

**Comment by timothycrosley** [comment]
This change has just been deployed to PyPI in version 5.5.0

Thanks!

~Timothy
