### ISSUE TITLE
Missing colorama leads to exception

### ISSUE THREAD

**Issue by darkclouder** [PyCQA/isort#1412]
https://github.com/PyCQA/isort/blob/9c80f02e3212091f14019fe238a62ae037a68e8d/isort/format.py#L117

Hey again :)

The current code unfortunately leads to an exception if colorama is not installed because the values are initialised on a class level and not only when an object is created.

**Comment by sztamas** [comment]
Hi @darkclouder 

Sorry for that and thanks for testing and reporting it!

It's funny that I was thinking about why I initialized those constants in such a strange way but couldn't remember it.

I'll fix it up!

Thanks,

Tamas
