### ISSUE TITLE
isort is ignorant to required dependency import order

### ISSUE THREAD

**Issue by theelderbeever** [PyCQA/isort#1416]
When developing packages sometimes modules need imported in a specific order for them to work. 

This is primarily an issue in __init\_\_ files. `isort` would reorder these to be alphabetical even though it is a breaking change.
```python
import B_module
import A_module # Internally imports B_module
```
Possible solutions?
- add a rules setting for "A_module depends on B_module"  meaning it wouldn't get sorted above it. 
- an isort.cfg setting to group `sections` together but don't reorder them inside the group.
- a isort.cfg setting to ignore files with a certain name ie: ignore all __init\_\_.py files

**Comment by timothycrosley** [comment]
Hi @theelderbeever,

Agree, it is common, especially in larger code bases, to have dependent imports. isort does provide some tools to work around this that I hope will be helpful!

> a isort.cfg setting to ignore files with a certain name ie: ignore all __init__.py files

This is supported! You can add to your .isort.cfg, `skip=__init__.py` and all init files will be skipped. Before isort got reasonably good at complex imports, this was actually the default. See: https://pycqa.github.io/isort/docs/configuration/options/#skip

Another set of options that are available to you:

- Use `force_to_top` for the imports that other imports depend on: https://pycqa.github.io/isort/docs/configuration/options/#force-to-top
- Use action comments to skip a few imports, a whole file, or just the section that has dependencies: https://pycqa.github.io/isort/docs/configuration/action_comments/
- Combine force_to_top combined with custom sections to make the dependencies clear: https://github.com/PyCQA/isort#custom-sections-and-ordering

I hope you find these solutions helpful! And please feel free to ask any follow up questions.

Thanks!

~Timothy

**Comment by theelderbeever** [comment]
Hey @timothycrosley 

I missed the `skip=__init\_\_.py` and 'force_to_top` options! Glad to see you already had these things taken care of! Love the module and using in my githooks!

Thanks,
Taylor
