### ISSUE TITLE
Can one specify list of files to run on from config file?

### ISSUE THREAD

**Issue by jamesbraza** [PyCQA/isort#1418]
Currently I invoke isort via:

```
isort .
```

I would like to add the `.` aspect into my config file (`pyproject.toml`) and invoke isort via:

```
isort
```

Is there already a config file option already present for this?

**Comment by timothycrosley** [comment]
@jamesbraza,

While I can understand the appeal of this, I'm afraid I'm hesitant to introduce such a config option within the main project. I feel it should always be safe for a user to run `isort` without worrying about it taking unexpected options depending on the project they are in. However, I could see having a single command that does this being useful to include in project directly, however for that I'd recommend using one of the more generic and widely available ways of extending console commands such as aliases or automatic environment files.

Thanks,

~Timothy

**Comment by jamesbraza** [comment]
Okay, thanks for responding and that all makes sense to me.

If you ever consider this, something similar can be found in `mypy` with the [`files` config file option](https://mypy.readthedocs.io/en/stable/config_file.html#import-discovery).
