### ISSUE TITLE
isort never settles on module docstring + add import

### ISSUE THREAD

**Issue by MatejNikl** [PyCQA/isort#1420]
I have a `file.py` with the following contents:
```python
"""module docstring"""

import os
```
repeatedly running `isort -a "import os" file.py` always prints:
```
Fixing /path/to/file.py
```
while the contents of the `file.py` never change.

I think `isort` is trying to achieve the following state:
```python
"""module docstring"""
import as
```
i.e. remove the blank line, as that's when it's output is empty.
isort==5.4.2

**Comment by timothycrosley** [comment]
@MatejNikl Thank you for reporting the issue! It has been fixed in develop and will be deployed to PyPI in the 5.5.0 release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
A fix for this issue has just been deployed to PyPI in version 5.5.0 of isort.

Thanks!

~Timothy
