### ISSUE TITLE
Fix spurious warnings in development tests

### ISSUE THREAD

**Issue by timothycrosley** [PyCQA/isort#1442]
- [ ] Move from hypothesis-auto to full hypothesis tests, utilizing [ghostwriter](https://hypothesis.readthedocs.io/en/latest/ghostwriter.html)
- [ ] Move testing of deprecated finders out of main test suite
- [ ] Remove ignoring of warnings

Split out from: https://github.com/PyCQA/isort/pull/1436

**Comment by anirudnits** [comment]
is anybody working on these? otherwise, I could give it a shot.

**Comment by timothycrosley** [comment]
I don't think any one is, thank you!

**Comment by anirudnits** [comment]
@timothycrosley sorry for the delayed response I've been a bit busy lately and couldn't find the time to work on it :(  If I get it right then

- Moving testing of deprecated finders out of main test suite could be done via `--ignore=tests/unit.test_deprecated_finders.py` in test.sh
- Remove ignoring of warnings would be to revert back the changes from https://github.com/PyCQA/isort/pull/1436.

**Comment by timothycrosley** [comment]
@anirudnits No worries! This issue in particular has no rush as @sztamas remediated the immediate issue well by ignoring the warnings. 

> Moving testing of deprecated finders out of main test suite could be done via --ignore=tests/unit.test_deprecated_finders.py in test.sh

That sounds right! We would then want to make sure that the coverage for the deprecated files is also ignored

> Remove ignoring of warnings would be to revert back the changes from #1436.

Yep! Exactly!

**Comment by anirudnits** [comment]
@timothycrosley  opened a pull request https://github.com/PyCQA/isort/pull/1477. Have a look :)

**Comment by timothycrosley** [comment]
@anirudnits Thanks for the great work on this! Closing this issue now :)
