### ISSUE TITLE
Adding import messes up module's docstring

### ISSUE THREAD

**Issue by MatejNikl** [PyCQA/isort#1444]
Have a blank line before the module's docstring (disregard the invisible character, I wasn't able to produce an empty first line in the code block without it):
```python
 
"""module docstring"""
```
running `isort -a "import os" file.py` modifies it to:
```python
 
import docstring"""
import os"""module
```
Am I doing something wrong or is this a bug?
isort==5.4.2

**Comment by timothycrosley** [comment]
A fix for this issue has just been deployed to PyPI in version 5.5.0 of isort.

Thanks!

~Timothy
