### ISSUE TITLE
Enable Code Climate and DeepSource for PyCQA/isort

### ISSUE THREAD

**Issue by hugovk** [PyCQA/isort#1449]
Welcome to your new home at PyCQA!

The README badges still link to the `timothycrosley/isort` ones, which have stopped running:

* https://codeclimate.com/github/timothycrosley/isort "Last develop build 9 days ago"
* https://deepsource.io/gh/timothycrosley/isort/?ref=repository-badge "Last analyzed 10 days ago"

They should be enabled for `PyCQA/isort` and the badges updated, or the badges removed.

**Comment by timothycrosley** [comment]
Thanks! And, thanks for reporting the no longer working integrations. I would have missed it for much longer! It looks like I don't have permission to add them directly anymore, and will need to reach out to one of the Owners of the PyCQA organization.
