### ISSUE TITLE
404 Upgrade guide link in error message

### ISSUE THREAD

**Issue by adamtheturtle** [PyCQA/isort#1459]
In one of my repos I see:

```
/Users/adam/.virtualenvs/sphinx-sub/lib/python3.8/site-packages/isort/settings.py:410: UserWarning: W0503: Deprecated config options were used: not_skip.Please see the 5.0.0 upgrade guide: bit.ly/isortv5.
```

bit.ly/isortv5 leads to https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/ which is a 404. It should be a link to https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/.

**Comment by timothycrosley** [comment]
Thanks for the notice! I've put in place a redirect to fix this issue!

**Comment by acatlla** [comment]
Hi @timothycrosley I notice the redirection to https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/ is not longer available and the link it should be https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html
