### ISSUE TITLE
no_sections only removes the newlines, not the sections

### ISSUE THREAD

**Issue by MartinThoma** [PyCQA/isort#1470]
A coworker would like to have everything (except for future) in one alphabetically sorted block. With `no_sections=True`, it's still building sections (e.g. the core-modules are on top), but just removes the newlines. Is it possible to combine sections?

**Comment by timothycrosley** [comment]
Sure!

Combine no_sections, with [force_alphabetical_sort](https://pycqa.github.io/isort/docs/configuration/options/#force-alphabetical-sort) if you want this while keeping from imports at the bottom, or combine it with [force_alphabetical_sort_within_sections](https://pycqa.github.io/isort/docs/configuration/options/#force-alphabetical-sort-within-sections) if you don't want to keep the from imports below the others.

**Comment by MartinThoma** [comment]
This sorts the "from x import y" over "import z". I still would want the "import" over the "from x import"s. Is that possible?

**Comment by timothycrosley** [comment]
@MartinThoma sorry the close was accidental as I had a stale copy of the issue open:

You could always accomplish this by pushing everything into stdlib:

```
 "sections": ["FUTURE", "STDLIB", "LOCALFOLDER"],
 "src_paths": [],
 "default_section": "STDLIB",
```

**Comment by MartinThoma** [comment]
Thank you!
