### ISSUE TITLE
Different defaults for force_grid_wrap in docs

### ISSUE THREAD

**Issue by dyve** [PyCQA/isort#1471]
The default value for `force_grid_wrap` is specified as both `2` (in text) and `0` (below text).

https://pycqa.github.io/isort/docs/configuration/options/#force-grid-wrap

<img width="657" alt="Schermafbeelding 2020-09-10 om 09 48 10" src="https://user-images.githubusercontent.com/82315/92696928-e991d700-f34a-11ea-9287-4309407b1dce.png">

**Comment by timothycrosley** [comment]
Thanks for reporting the confusing documentation!

This has been improved here: https://pycqa.github.io/isort/docs/configuration/options/#force-grid-wrap

~Timothy

**Comment by dyve** [comment]
Thanks @timothycrosley! Thanks for isort!
