### ISSUE TITLE
Goal Zero: Full testing of stdin CLI Options

### ISSUE THREAD

**Issue by timothycrosley** [PyCQA/isort#1472]
This ticket is part of an aspirational goal for the isort project to achieve zero regressions through the remaining life of the 5.0.0 release, without slowing down the release velocity.

Currently, as mentioned by @karrtikr there have been an unfortunate number of regressions in the 5.x series involving the usage of streaming from stdin. This ticket represents the work to expand the automated test suite to ensure every CLI flag is tested against this mode of usage to avoid further regressions.

**Comment by anirudnits** [comment]
@timothycrosley if this not very urgent, I can work on this and maybe get around by this weekend(?) Obviously that's if anybody is yet to actual start working on this.

**Comment by timothycrosley** [comment]
@anirudnits that would be very appreciated! No urgency on this ticket.

**Comment by timothycrosley** [comment]
Closing as @anirudnits added a very comprehensive set of tests to the project,

Thanks!

~Timothy
