### ISSUE TITLE
Offical github action?

### ISSUE THREAD

**Issue by michael0liver** [PyCQA/isort#1493]
It would be nice to have an official GitHub action 😄, are there any plans for it?

**Comment by timothycrosley** [comment]
There are now :wink: I think it would be nice to have an official github action and am happy to accept a PR that adds one

**Comment by jamescurtin** [comment]
I believe it is preferable for an action to live in a standalone repo: in addition to it being a cleaner division, actions are semantically versioned based on released tags, which would conflict with the tagging scheme for the isort package.

For this reason, I've created [`python-isort`](https://github.com/jamescurtin/isort-action)  action. I've also created this [demonstration repository](https://github.com/jamescurtin/test-isort-action) that shows examples of both a passing and a failing check.

If you have an interest in moving this action into an "official" isort organization, let me know and I can transfer the repo.

**Comment by timothycrosley** [comment]
@jamescurtin this looks great! I agree with your assessment that it should be a separate repository. I've added you to the `isort` organization which should give you the power to move transfer this repository into there. That would make it the first *official* isort extension.

Would you be willing to:

- Mark the repository as using the MIT license
- Submit a small PR here to add documentation for this new action?

Thanks!

~Timothy

**Comment by jamescurtin** [comment]
Sounds great! The license has been added & the repo is now in the `isort` organization.

Documentation PR has been submitted as well.
