### ISSUE TITLE
Newline between first import and copyright/license header

### ISSUE THREAD

**Issue by gwenzek** [PyCQA/isort#1495]
When upgrading between `isort 5.4.2` and `isort 5.5.3` I noticed that `isort` wanted to remove the line between the header and the first import:

```
 # This source code is licensed under the MIT license found in the
 # LICENSE file in the root directory of this source tree.
 #
                  <- isort 5.5.3 want to drop this line
 import re
```

Is this an expected behavior ? Is there a corresponding configuration option to control this behavior ?

**Comment by anirudnits** [comment]
I can't reproduce the problem with the given input. Did you specify any other configuration like `--fass` or something?

**Comment by gwenzek** [comment]
Ahah, it was apparently due to the `float_to_top=True`.
Disabling this does keep the blank line in 5.5.3
But the behavior of `float_to_top` did change between the two versions and this behavior is not documented.

Fixed for me, I'll just remove the `float_to_top` option.

**Comment by timothycrosley** [comment]
@gwenzek, sorry this led to confusion! I've clarified the behaviour in the documentation

~Timothy

**Comment by gwenzek** [comment]
Thanks Timothy gor this great tool, and the quality of the documentation !
