### ISSUE TITLE
Prevent isort from running on virtualenv files via editor?

### ISSUE THREAD

**Issue by pikeas** [PyCQA/isort#1500]
```
[tool.isort]
profile = "black"
verbose = true
```

I have VS Code configured to use isort locally:

```
{
  ...
  "python.sortImports.path": "${workspaceFolder}/.venv/bin/isort",
}
```

When saving a file in the virtualenv directory, isort unexpectedly runs. Here's what VS Code's output pane shows:

```
> <project path>/.venv/bin/isort - --diff
cwd: <project path>/.venv/lib/python3.8/site-packages/<some module>
Error: Invalid patch string: else-type place_module for <some import> returned STDLIB
```

The actual error seems potentially related to https://github.com/PyCQA/isort/issues/1469 but I have confirmed that the version of isort in the virtualenv is the latest 5.5.3.

However, the surprising thing is that isort shouldn't run at all. It doesn't seem to consider https://pycqa.github.io/isort/docs/configuration/options/#skip . I've tried adding skip_gitignore as well (which includes `.venv/`, to no avail.

**Comment by pikeas** [comment]
Update: this is a bit of a [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug), behavior is different with and without `verbose = true`! I imagine this is because VS Code isn't equipped to handle the additonal verbose output.

With verbose off, there's no error, but isort continues to (unexpectedly) run.

**Comment by char101** [comment]
`isort` is run via `stdin` thus it has no concept of the file path. When run like that it should be the responsibility of the editor/plugin to skip files.

**Comment by timothycrosley** [comment]
@char101 is correct regarding it being unaware of path - however you should be able to configure vs code to tell it the path if you would like to use a normal isort config, using setting path: https://pycqa.github.io/isort/docs/configuration/options/#settings-path
