### ISSUE TITLE
Import all (*) from modules better be positioned before explicit local imports

### ISSUE THREAD

**Issue by besfahbod** [PyCQA/isort#1504]
In general, it's recommended to *not* use "import all" pattern, or at least not without explicit `__all__` defined.

However, many code-bases still do so, for good reasons, such as reducing friction in adding new items to a shared library.

Now, assuming we're okay with `import *` in general, and specifically `from _<dir-name> import *` forms, the example below demonstrates a problem when having `import *` statement at the end of the local-imports list, instead of first.

----

Here's the structure of the package `bar`, which has an internal module `_foo`, as well as module `_bar` that's considered the "main" module of the package.

The file contents are like:

`bar/__init__.py`:
```
from ._foo import Any, All, Not # ...
from ._bar import *

# [...]
```

`bar/_bar.py`:
```
from typing import Any, List # ...

# [...]
```

`bar/_foo.py`:
```
class Any(...):
    # [...]

class All(...):
    # [...]

class Not(...):
    # [...]

# [...]
```

In this set up, the class `Any` from `typing` is overshadowing the class `Any` defined in `bar/_foo.py`, and re-export explicitly as part of the "public API" of package `bar`.

If we change keep `import *` statements at the beginning of local-imports block, we would prevent such *implicit* overrides from external imports, reducing friction for developers.

So, `isort` would modify `bar/__init__.py` to look like:

```
from ._bar import *
from ._foo import Any, All, Not # ...

# [...]
```

----

I don't know if this has been discussed before (really hard to search for terms "import" and "all" in this repo), but like to suggest updating `isort` to change the behavior here.

What do you think?

**Comment by timothycrosley** [comment]
@besfahbod I think this is a great idea! This will likely surprise many who encounter, as all other non strictly alphabetical sorting behaviour does, but I think that can be solved with some documentation updates. Overall, I think this the exact kind of refinement that I'd love to include in isort now that it is a more mature tool.

Thanks!

~Timothy

**Comment by besfahbod** [comment]
Thanks, @timothycrosley! Agreed.

I like to also point out the fact that, positing of symbols, such as `*`, are never really set in stone in "alphabetic" orderings, as a general rule. It's true that many programmers are usually more comfortable with ASCII ordering of characters (and this is what I use by default in my editor, as well); however, sometimes "keeping all symbols together", before or after alpha-numerics, is usually a better pattern.

Considering that, and to make the semantics easier, I like to suggest something like this for the guide-level explanation: Alphabetical ordering is performed by having all non-alpha-numeric (symbol) characters first, then numerals, and alpha characters.

**Comment by timothycrosley** [comment]
This has been implemented in develop (using the new `--star-first` option) with plans to make default in next major release.

Thanks!

~Timothy
