### ISSUE TITLE
Provide an easy way to see all files isort will be ran against.

### ISSUE THREAD

**Issue by timothycrosley** [PyCQA/isort#1511]
Currently, it is more difficult than necessary to see what files isort plans on formatting.
See: https://twitter.com/tdhopper/status/1308101586321891328.

This ticket represents the work to make it easy to get at this information from the CLI.

The proposed interface will be `isort . --show-files`. When that flag is passed in all files will be listed, each on their own line.

**Comment by anirudnits** [comment]
@timothycrosley I can take this on 👍
