### ISSUE TITLE
Why is not possible to load the "files" field from a settings file?

### ISSUE THREAD

**Issue by garciparedes** [PyCQA/isort#1513]
As I see in the [documentation](https://pycqa.github.io/isort/docs/configuration/options/#files), the `files` field can not be set up trough a config file. Is there any reason for this restriction?

For me, it would be easiest to set the file paths in the config files (`setup.cfg`) instead of directly from the CLI. My basic config is `isort $DIRECTORY_PATH --recursive` so I would like to move those options to the config file.

**Comment by timothycrosley** [comment]
The reason is that it makes typing `isort` inconsistent. Usually, it simply gives you a helpful overview without performing any actions, if this could be configured via the CLI, then users of isort would have to always second guess what the command would do depending on the directory they were in. Additionally, this is something that I think is better and more universally solved outside of isort itself. Scripts, aliases, etc all over a simple way to do this. And, since `--recursive` is deprecated, generally simply doing `isort .` does what is intended.

**Comment by timothycrosley** [comment]
For some additional context: The Black project (which is commonly used in conjunction with isort) also doesn't support such options, for the same reasons: https://github.com/psf/black/issues/861. If Black ever supports such an option, I'll think about doing it as well for isort. In general though I think it can make sense to do automatic running for non-mutating tools, but I personally would find it to be a terrifying experience to have a tool that mutates source, do that when I just enter the name of the tool and nothing else. Especially so if it only happens sometimes depending on what directory I am in.

**Comment by garciparedes** [comment]
Thanks for your amazing explanation @timothycrosley! 

Then, if I've understood you well, in the future the file globbing should be performed with some external tool apart from `isort`. Am I right?

**Comment by garciparedes** [comment]
I think that makes sense, especially for large code bases in which don't make sense to run `isort` or `black` around all files each time. It seems more interesting to pick only the ones with changes, so that I agree with you that this task should be performed by another external tool/script/etc. Thanks for your help!

**Comment by timothycrosley** [comment]
Happy to do what I can to help!
Yes, I think that's right.

### Some example approaches from OpenSource projects in the wild:

**Scripts**: This is the approached used by isort itself and projects like fastAPI.

- https://github.com/PyCQA/isort/blob/develop/scripts/clean.sh#L4
- https://github.com/tiangolo/fastapi/blob/master/scripts/format.sh

**Tox**: Another approach I've seen is to use tox to kick-off the script

- https://github.com/PyCQA/pylint/blob/master/tox.ini#L36

**[Pre-commit](https://pre-commit.com/)**: Is a great way to automate this at the time of a commit.

- https://github.com/psf/black/blob/master/.pre-commit-config.yaml

**DirEnv/AutoEnv**: In the past I used autoenv or direnv for this kind of thing, as it allows simple aliases to take effect as soon as you cd into a directory: https://direnv.net/.

- https://github.com/hugapi/hug/blob/develop/.env#L65
