### ISSUE TITLE
Bug --float-to-top doesn't work after isort: off and then isort: on

### ISSUE THREAD

**Issue by sztamas** [PyCQA/isort#1519]
Hi @timothycrosley ,

This is a bug isn't it?
_Found it while trying to increase the test coverage in ``core.py``._

Given ``t.py``:

```python
def foo():
    pass

import a

# isort: off
import stays_here

# isort: on
x = 1
import floats_up_again

def bar():
    pass
```

I expected ``import floats_up_again`` to float up to the top of the file, but it floats up to just the top of it's own "section".

```python
▶ isort -d --float-to-top t.py
import a


def foo():
    pass

# isort: off
import stays_here

# isort: on
import floats_up_again

x = 1

def bar():
    pass
```

What do you think?

**Comment by timothycrosley** [comment]
It was the initial design (intentionally) to work this way, however I do think it's not ideal and would be better if it floated imports all the way to the top. If we improve the behaviour for float to top combined with off and on comments it will just be important to make sure that `# isort: split` comments continue to work the way that they do.

**Comment by sztamas** [comment]
Hmmm, you can argue both ways I guess.

Based on the current documentation the imports should float to the **top of the file**.

https://pycqa.github.io/isort/docs/configuration/options/#float-to-top

However, because I expect ``--float-to-top`` to be used as a convenience that you run from time to time to clean up after a coding session when you inserted imports all over the place. It seems a bit strange to use that interactive method of clean-up with the more permanent ``isort: on/off`` comments to control what gets floated up and what stays in place.

But then again, I could imagine someone relying on isort to be "lazy" permanently. ie.have ``float-to-top`` on as a config and never have to care where you put your imports while coding.
In that case, being able to keep some imports in place, but move everything to the top might be useful and can be achieved by using the ``on/off`` directives.

So far I've added some tests that characterize the current behaviour and also take branch coverage in ``core.py`` to `100%`.

https://github.com/PyCQA/isort/pull/1520

Please let me know if you want this changed or not.
If not we should probably at least update the ``float-to-top`` docs to describe the current behaviour when used with off and on comments.

**Comment by timothycrosley** [comment]
I **think** it makes sense to fix it, however, we probably need to update the docs either way as we would still want a `split` to effectively trigger this behaviour intentionally moving some imports below the literal top of the file. I'm marking it for the 5.7.0 milestone which should give some time for other users of isort that use `--float-to-top` to chime in if they have strong opinions.

**Comment by timothycrosley** [comment]
Closing this and tagging it for the next release (as it has now been the behavior for so long I think it makes sense to keep it for the duration of 5.x.x)
