### ISSUE TITLE
Single line import with vertical hanging indent

### ISSUE THREAD

**Issue by machinekoder** [PyCQA/isort#1530]
Looks like this one still exists: https://github.com/PyCQA/isort/issues/365

```
from robot_ui.pathpilot.robot.jog.cartesian_jog_control import JOG_COMMAND_TOPIC as CARTESIAN_JOG_CMD_TOPIC
```

is formatted to

```
from robot_ui.pathpilot.robot.jog.cartesian_jog_control import \
    JOG_COMMAND_TOPIC as CARTESIAN_JOG_CMD_TOPIC
```

with settings

```
[settings]
line_length = 80
multi_line_output = 3
include_trailing_comma = True
ensure_newline_before_comments = True
```

expected:

```
from robot_ui.pathpilot.robot.jog.cartesian_jog_control import (
    JOG_COMMAND_TOPIC as CARTESIAN_JOG_CMD_TOPIC,
)
```

**Comment by timothycrosley** [comment]
Hi @machinekoder,

You can achieve the output you desire by setting [use_parentheses](https://pycqa.github.io/isort/docs/configuration/options/#use-parentheses) to true:

```
[settings]
line_length = 80
multi_line_output = 3
include_trailing_comma = True
ensure_newline_before_comments = True
use_parentheses = True
```

The exact issue found in that case (an single from import that could part of a group)  is indeed still fixed - however it aliased imports are special cased by default and never in groups (unless [combine_as](https://pycqa.github.io/isort/docs/configuration/options/#combine-as-imports) is set) -- and so they have always used whatever the default single-line continuation behaviour is.

I do think longer term it would make sense to automatically change the default value of `use_parentheses` based on the wrap mode, however that may need to wait for the next major release.

Let me know if I've helped to resolve your immediate issue.

Thanks!

~Timothy

**Comment by machinekoder** [comment]
@timothycrosley Thanks, indeed that solve my problem.
