### ISSUE TITLE
Provide API and CLI to list and stream imports 

### ISSUE THREAD

**Issue by timothycrosley** [PyCQA/isort#1536]
isort is now exceptional at finding all imports, even nested ones, inside of Python source files of any size quickly. I think it would be beneficial to expose this functionality for downstream use, both from the CLI and via the isort API. From the CLI instead of adding yet another additional flag, it may make sense to make an entire separate command (such as as isort_identify_imports or similar.)

**Comment by timqsh** [comment]
Hi! Looking into this issue.
