### ISSUE TITLE
Move documentation pieces from README to dedicated markdown files.

### ISSUE THREAD

**Issue by timothycrosley** [PyCQA/isort#1544]
isort used to rely almost completely on it's README for documentation. However, it now has a nice documentation website in https://pycqa.github.io/isort/. Work should be done to move sections from the README to dedicated markdown documentation pages. Can be done in multiple PRs, before taking a section on - please put a comment here to say which section to avoid duplication of effort.

**Comment by confusedcoder1** [comment]
Hey, I'd like to work on this. But I was looking at the site, almost all sections seem updated? What ones exactly are to be moved?

**Comment by timothycrosley** [comment]
Good question! I think in particular the below sections should be moved into sub-pages of configuration on the website (https://pycqa.github.io/isort/docs/configuration/action_comments/ as an example of where they should move to).

- https://github.com/PyCQA/isort#multi-line-output-modes
- https://github.com/PyCQA/isort#custom-sections-and-ordering
- https://github.com/PyCQA/isort#auto-comment-import-sections
- https://github.com/PyCQA/isort#adding-an-import-to-multiple-files & https://github.com/PyCQA/isort#removing-an-import-from-multiple-files should probably be one page
- https://github.com/PyCQA/isort#git-hook
- https://github.com/PyCQA/isort#setuptools-integration

**Comment by confusedcoder1** [comment]
Okay, on it!

**Comment by PriyanshTri** [comment]
can you assign me ?

**Comment by timothycrosley** [comment]
@confusedcoder1 are you still working on this?

**Comment by PriyanshTri** [comment]
I don't think she is still working on it.... Can you assign this to me?

**Comment by confusedcoder1** [comment]
I wasn't assigned to this, @PriyanshTri. You can work on it. I started this but I'm on some time constraints right now. So I cannot complete it. Apologies @timothycrosley .

**Comment by timothycrosley** [comment]
This has now been completed
