### ISSUE TITLE
Empty line added in import that should be skipped

### ISSUE THREAD

**Issue by samdaviesudina** [PyCQA/isort#1548]
I'm seeing an issue with `5.6.0` that I wasn't seeing with `5.5.3`.

Before running `isort`:
```python
from tools.dependency_pruning.prune_dependencies import (  # isort:skip
    prune_dependencies,
)
```

After running `isort`:
```python
from tools.dependency_pruning.prune_dependencies import (  # isort:skip

    prune_dependencies,
)
```

Config:
```
[isort]
profile = black
float_to_top = True
```

If I remove `float_to_top = True` from the config, the line doesn't get added anymore.

Thanks!

**Comment by timothycrosley** [comment]
Thanks for reporting! This has been fixed in isort 5.6.2
