### ISSUE TITLE
On Ubuntu 12.04 isort thinks that `binascii` is 3rd party, and that `cv2` is stdlib

### ISSUE THREAD

**Issue by drothlis** [PyCQA/isort#157]
- `binascii` is part of the python stdlib but `isort` treats it as a 3rd party module.
- `cv2` is from `apt-get install python-opencv`, but `isort` treats it as part of the python stdlib.

This doesn't happen on my mac (`isort` behaves correctly); it only happens on my [Travis CI job](https://travis-ci.org/drothlis/stb-tester/builds/25047971) which is running Ubuntu 12.04.

What information can I gather to help you diagnose this?

**Comment by PanderMusubi** [comment]
Please vote for https://bugs.launchpad.net/ubuntu/+bug/1380529 to get isort supported and shipped on Ubuntu and Debian.
