### ISSUE TITLE
isort removes duplicated imports with different aliases and breaks code

### ISSUE THREAD

**Issue by mvaled** [PyCQA/isort#1580]
isort 5.5.3 changes this:

```python
from datetime import datetime as d, datetime
```

to this:

```python
from datetime import datetime as d
```

But that breaks the code.  

I use this idiom in tests where I want to put values like `d(2020, 10, 21)`, but I want my code to be clear when saying things like `isinstance(x, datetime)` and not `isinstance(x, d)`.

Currently, I'm getting away with this by using `# isort: skip`.

**Comment by timothycrosley** [comment]
Hi @mvaled,

I'm sorry this error affected you! This has already been fixed in newer versions of isort. Simply upgrading to the latest version should fix this issue for you. If it does not please let us know.

Thanks!

~Timothy

**Comment by mvaled** [comment]
@timothycrosley 

Great! Thanks.  I can confirm that isort 5.6.4 does keep both imports.
