### ISSUE TITLE
Bug: Isort dropping # noqa comment

### ISSUE THREAD

**Issue by Pacu2** [PyCQA/isort#1594]
Version: ```5.6.4```
Python 3.7
**Description**
Isort drops # noqa comment while sorting, when two imports from the same file/module exists, and one of them exceeds the max line length.

**Steps to reproduce**
Create two files with content as below. Sort `test_isort.py` with isort

`test.py`
```
class TestTestTestTestTestTest1:
    pass

class TestTestTestTestTestTest2:
    pass

class TestTestTestTestTestTest3:
    pass

class TestTestTestTestTestTest4:
    pass

class TestTestTestTestTestTest5:
    pass
```

`test_isort.py`
```
from .test import TestTestTestTestTestTest1  # noqa: F401
from .test import TestTestTestTestTestTest2, TestTestTestTestTestTest3, TestTestTestTestTestTest4, TestTestTestTestTestTest5  # noqa: F401
```

**Actual result:**
```
from .test import TestTestTestTestTestTest1  # noqa: F401; noqa: F401
from .test import (TestTestTestTestTestTest2, TestTestTestTestTestTest3,
                   TestTestTestTestTestTest4, TestTestTestTestTestTest5)
```
As you can see, #noqa comment was dropped from the second line, resulting in linter failling. 

**Expected result:**
Imports should be joined together, single # noqa comment exists.

**Comment by anirudnits** [comment]
Just to be clear, the expected result would look like
````
from .test import (TestTestTestTestTest1, ... # noqa: F401
                   ...,
                   TestTestTestTestTest5)

**Comment by Pacu2** [comment]
@anirudnits That's right, thanks

**Comment by Borda** [comment]
That seems to be a dead lock with `flake8` as PEP8 complains about unused imports and `isort` moves it...
just for the record, this is our config:
```
[isort]
line_length = 120
order_by_type = False
multi_line_output = 3
include_trailing_comma = True
honor_noqa = True
```
this is the input and also expected output:
```python
from pl_bolts.models.self_supervised.moco.transforms import Moco2EvalCIFAR10Transforms  # noqa: F401
from pl_bolts.models.self_supervised.moco.transforms import (  # noqa: F401
    Moco2EvalImagenetTransforms,
    Moco2EvalSTL10Transforms,
   ...
)
```
and this is the result:
```python
from pl_bolts.models.self_supervised.moco.transforms import Moco2EvalCIFAR10Transforms  # noqa: F401; noqa: F401
from pl_bolts.models.self_supervised.moco.transforms import (
    Moco2EvalImagenetTransforms,
    Moco2EvalSTL10Transforms,
   ...
)
```

**Comment by timothycrosley** [comment]
@Borda,

Sorry to hear you are experiencing this issue as well! As a friendly reminder, in case you or others in this friend are unaware, while the project certainly prioritizes fixing issues like this, you should never feel stuck! isort provides many escape hatches for any disagreements with other tools, of particular good use for this issue is `isort: off` and `isort: on` action comments as detailed in the documentation here:

https://pycqa.github.io/isort/docs/configuration/action_comments/#isort-off

**Comment by Borda** [comment]
@timothycrosley thanks for such swift reply and for this nice too
I fully understand that there can be some disagreements with other formatting tools but as far as I know `flake8` is only checking compliance with PEP8, right?

**Comment by timothycrosley** [comment]
This is now fixed in develop and will make its way out in the next release (5.8.0)

Thanks!

~Timothy
