### ISSUE TITLE
Passing filename / extension when using stdin to support `.pyi` files w/ black

### ISSUE THREAD

**Issue by sbdchd** [PyCQA/isort#1596]
With the black profile, not sure about others, formatting is dependent on the extension.

When using stdin to format a file the extension information isn't passed along, 
so there isn't a way to format `.pyi` files the same as when passing the file path.

## Example

example file `main.pyi`:

```python
from typing import Any

class Bar:
    def foo(self, arg: Any) -> bytes: ...
```

```
./.venv/bin/isort --profile=black main.pyi --diff
```
No changes necessary.

and via stdin

```
❯ cat main.pyi | ./.venv/bin/isort --profile=black - --diff
--- :before	2020-11-11 22:48:00.874612
+++ :after	2020-11-11 22:48:00.874650
@@ -1,4 +1,5 @@
 from typing import Any
+
 
 class Bar:
     def foo(self, arg: Any) -> bytes: ...
```

## conclusion

I think one solution is to specify the extension manually, or give isort a fake
filename to use.

```python
cat main.pyi | ./.venv/bin/isort --profile=black --extension=.pyi - --diff
# or 
cat main.pyi | ./.venv/bin/isort --profile=black --filename=main.pyi - --diff
```

rel: https://github.com/PyCQA/isort/issues/942
rel: https://github.com/microsoft/vscode-python/issues/14702

**Comment by timothycrosley** [comment]
Thanks for this well thought out issue! I've always meant for isort to support this, and indeed it already does for API based, but until now this functionality was not exposed to the CLI.

In develop, to be released with 5.7.0 some time this month, both features (specifying the filename and specifying the extension formatting to use) are now available:

```
echo -e "import b\nimport a\ndef x():\n   pass" | isort - --filename actual_disk_location.pyi
echo -e "import b\nimport a\ndef x():\n   pass" | isort - --ext-format pyi
```

Thanks!

~Timothy
