### ISSUE TITLE
isort doesn't want for EOF when reading from stdin

### ISSUE THREAD

**Issue by utkarshgupta137** [PyCQA/isort#1599]
When reading from stdin, isort starts outputting without waiting for EOF. This is fine when one wants to pipe `cat file.py` output, but it makes it impossible to just copy-paste some python code and get it with imports sorted.

**Comment by timothycrosley** [comment]
Hi @utkarshgupta137,

I can understand the desire to be able to copy and past code and have it quickly sorted, but might I suggest using https://pycqa.github.io/isort/docs/quick_start/0.-try/ or vs code or QuickPython to do it?

It is by design that isort doesn't wait for EOF. Doing so would make the designed for case that you described (piping files as used by certain integration such as VS Code) perform worse and increase the memory requirement of isort. isort uses a streaming architecture and sorts as it sees contiguous areas of imports.

Thanks!

~Timothy

**Comment by utkarshgupta137** [comment]
I'm writing an isort (+ black) plugin for python. I wish to isort the contents in buffer, without having to save the file.

Can you suggest a way to do it (using js) other than spawning a python process or writing to a temp file & copying it over?

**Comment by utkarshgupta137** [comment]
If you're interested in adding this feature, I'm willing to work on it if you can point me in the right direction.

**Comment by timothycrosley** [comment]
@utkarshgupta137 an atom plugin for isort + black sounds great!

If I understand correctly, your goal then is to essentially keep the pipe open and keep sending content to it? 
I'm not really familiar enough with non web JS to know off-hand how to accomplish this in that scenerio, but I think it is separate from the goal to read into the tickets implied description asking for isort to buffer until EOF. Here's a Python example that shows a pipe to isort that is kept open over multiple runs:

```python
from subprocess import PIPE, Popen

proc = Popen(("isort", "-"), stdin=PIPE, stdout=PIPE)
proc.stdin.write(
    """
import b
import a
<--END-->
""".encode()
)

def text_until_end():
    text = ""
    while True:
        line = proc.stdout.readline()
        if line == "<--END-->":
            break
        text += line
    return text


sorted1 =  print read(p.stdout.fileno(), 1024),

while line != "<--END-->":
    sorted1 = proc.stdout.readline()

proc.stdin.write(
    """
import c
import b
""".encode()
)
sorted2 = text_until_end()

print(
    f"""
sorted1:
{sorted1}

sorted2:
{sorted2}
"""
)
```

**Comment by utkarshgupta137** [comment]
No, I don't intend to keep the buffer open. I'm using node.js's child_process (Actually a wrapper provider by atom). I'm doing:

```
      process.stdin.write(editor.getText());
      process.stdin.end();
```
But in stdout, I'm only getting: "Broken 1 paths."

**Comment by utkarshgupta137** [comment]
Actually, it looks _my_ problem was solved by passing `shell=true` to child_process. You can keep this issue open if you wish to add this functionality.

**Comment by timothycrosley** [comment]
I think you just need to find a different approach for accumulating the stdout from isort, I've never done this kind of JS task before but my first attempt worked:

```
var spawn = require('child_process').spawn,
    child = spawn('isort', ["-"]);

child.stdin.setEncoding('utf-8');

stdout = ''
child.stdout.on('data', function (data) {
    stdout += data
});

child.stdin.write("import b\nimport a\n");
child.stdin.end();

console.log("stdout:", stdout);
```

**Comment by timothycrosley** [comment]
Glad to hear you were able to find a solution! If you run into any other snags let me know! And if you publish your plugin I'll make sure to integrate it into the isort documentation

**Comment by utkarshgupta137** [comment]
Thanks for putting in the time to write code in both py & js :) 🥇

**Comment by utkarshgupta137** [comment]
Hey, I've added a link to my package: https://atom.io/packages/formatters-python in the wiki. Hope that is okay :)
