### ISSUE TITLE
isort 4 vs 5 - first party grouping with third party

### ISSUE THREAD

**Issue by mgresko** [PyCQA/isort#1600]
isort 4 first party was separated correctly.  isort 5 no matter what i do my first party code imports get grouped with third party.  Here is the directory layout

```
myapp:
   myapp:
       __init__.py
      main.py
      utils.py 
   pyproject.toml
```

Config:

```
[tool.isort]
known_typing = "typing,types,typing_extensions,mypy,mypy_extensions"
sections = "FUTURE,TYPING,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
include_trailing_comma = true
default_section = "FIRSTPARTY"
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
line_length = 120
```

I have tried to add `src_paths: "myapp"` and `known_first_party = "myapp"`.  Does not make a difference

Diff (--interactive): 
```
 from typing import Union
 
 import base64
 import json
 from contextlib import contextmanager
 from dataclasses import dataclass
 
 import botocore
 import typer
 from boto3.session import Session
-
 from myapp.models import Secret 
```

^ trying to group myapp with third party

I am probably missing something obvious.. any help would be appreciated.  Thanks!

**Comment by timothycrosley** [comment]
:wave: @mgresko,

I'm sorry you're experiencing this issue! I think it should be resolved for you simply by removing this config setting:

`default_section = "FIRSTPARTY"`

Let me know if this works for you,

Thanks!

~Timothy

**Comment by mgresko** [comment]
💥  that was it.  Thank you!
