### ISSUE TITLE
--color output does not seem to work in CI

### ISSUE THREAD

**Issue by exhuma** [PyCQA/isort#1602]
While the color output works on a normal console, it fails in CI. In the attached screenshot I would expect the highlighted lines to be colored considering that isort is run with the `--color` flag.

My guess is that it does not detect the output as a "real interactive shell" and assumes that it does not support escape codes. But in this case it does. It would be nice (and sufficient) to have a `--force-color` flag to disable this auto-detection.

![image](https://user-images.githubusercontent.com/65717/100104141-193e7e80-2e66-11eb-9a80-fe94607dbfea.png)

**Comment by timothycrosley** [comment]
This seems to be an upstream issue with the colorama package isort uses to colorize terminal text: https://github.com/tartley/colorama/issues/214 in the linked issue you can see a workaround involving setting an environment variable.

**Comment by RuRo** [comment]
This issue can also be avoided by setting `strip=False` during `colorama.init`. Would you accept a pull request that performs a late initialization of `colorama` with `strip=False` if `isort`s `config.color_output` is `True`?
