### ISSUE TITLE
Override float_to_top from the command line

### ISSUE THREAD

**Issue by MarcoGorelli** [PyCQA/isort#1603]
It looks like it's not currently possible to override `float_to_top` from the command-line - would something like `--float-to-top=0` be a welcome addition to `isort?

For a use-case, see [here](https://github.com/nbQA-dev/nbQA/issues/488) where someone has `float_to_top` set in their `.isort.cfg` file, but they want to override it when running `isort` on Jupyter Notebooks (via [nbqa](https://github.com/nbQA-dev/nbQA))

**Comment by timothycrosley** [comment]
This is fixed in develop and will make it's way into the 5.7.0 release of isort

**Comment by MarcoGorelli** [comment]
Awesome, thanks!
