### ISSUE TITLE
Force indentation of long absolute import

### ISSUE THREAD

**Issue by MatusBako** [PyCQA/isort#1611]
I have been looking for a functionality presented below, but haven't been lucky so far.

Input:
```python
from package.which.name.is.too.long.to.fit.into.line import function
```

Actual output:
```python
from package.which.name.is.too.long.to.fit.into.line import
    function
```

Expected output (given reasonable line length):
```python
from package.which.name.is.too.long.\
    to.fit.into.line import function
```

Also choosing wether dot is at the end of previous line or at the start of next line would make sense.

**Comment by timothycrosley** [comment]
Hi @MatusBako, thank you for reporting! I'm sorry this issue has affected you. This particular issue is already tracked in the following ticket: https://github.com/PyCQA/isort/issues/1531. So, I'll close this but you can track the progress or outcome of any changes on that ticket.

Thanks!

Timothy
