### ISSUE TITLE
Example for using a config file is broken (extraneous quotes)

### ISSUE THREAD

**Issue by hunter-moeller** [PyCQA/isort#1617]
https://pycqa.github.io/isort/docs/configuration/black_compatibility/
![image](https://user-images.githubusercontent.com/42941044/102934698-a9c2ab80-4472-11eb-9a95-ffbefddf2a31.png)

This snipped has `profile = "black"` but including quotes like that is not supported:
```
$ isort foo.py
Traceback (most recent call last):
  File "{redacted}\isort-script.py", line 9, in <module>
    sys.exit(main())
  File "{redacted}\isort\main.py", line 875, in main
    config = Config(**config_dict)
  File "{redacted}\isort\settings.py", line 314, in __init__
    raise ProfileDoesNotExist(profile_name)
isort.exceptions.ProfileDoesNotExist: Specified profile of "black" does not exist. Available profiles: black,django,pycharm,google,open_stack,plone,attrs,hug.
```

**Comment by anirudnits** [comment]
@hunter-moeller thanks for raising this issue, I believe when you tried to use the _profile_ setting you put them under _.isort.cfg_ file? Now this example actually corresponds to a _pyproject.toml_ file. If you look at the individual config file options here https://pycqa.github.io/isort/docs/configuration/config_files/, the syntax for all the different config files are specified including _.isort.cfg, pyproject.toml_ etc. The confusion stems from the heading which might indicate that the settings are for _.isort.cfg_. 

Hope this helps.

**Comment by hunter-moeller** [comment]
Ah thanks for explaining.  Yep I was using an `.isort.cfg` file and yes it was the heading that threw me off.
