### ISSUE TITLE
Invalid order when there is a local file / folder conflicting with module names

### ISSUE THREAD

**Issue by emadboctorx** [PyCQA/isort#1619]
Here is an example in which [wandb](https://github.com/wandb/client) creates a folder called wandb in the working directory and then `wandb` is placed with local imports (group 3) while it should be with the external libraries (group 2) and I verified the problem by deleting the local `wandb` folder, and as expected, it's placed in the second group.

```
from collections import deque
from time import perf_counter

import gym
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, Dense, Flatten, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

import wandb
from Chapter06.lib import wrappers
from utils import activate_gpu_tf
```

After deleting `wandb` folder:

```
import gym
import numpy as np
import tensorflow as tf
import wandb
from tensorflow.keras.layers import Conv2D, Dense, Flatten, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

from Chapter06.lib import wrappers
from utils import activate_gpu_tf
```

**Comment by anirudnits** [comment]
Hello @emadboctorx, _isort_ looks in the src path to identify if some module is first party or not and so the different behavior with and without the _wandb_ directory. You can configure _isort_ to forcefully recognize some module as first party or third party using https://github.com/PyCQA/isort/blob/develop/docs/configuration/options.md#known-first-party or https://github.com/PyCQA/isort/blob/develop/docs/configuration/options.md#known-third-party

**Comment by emadboctorx** [comment]
But in that case, it just checks for the filename without checking whether it is a module / package, what you suggested would fix the issue. I brought this up looking for non-forced ways to automatically differentiate parties but as this looks like it is intentional, I will close the issue, thanks.
