### ISSUE TITLE
Bug: Isort adds double comma if line has a very long comment

### ISSUE THREAD

**Issue by Pacu2** [PyCQA/isort#1621]
Isort version 5.6.4
Reproduced on windows + macos
Python 3.7

Consider this example:
```
from .test import (
    TestTestTestTestTestTest2 as TestTestTestTestTestTest1  # Some really long comment bla bla bla bla bla
)
```

With this config: (not sure which setting is responsible for that)
```
[isort]
profile = black
```

**Actual result:**
```
from .test import (
    TestTestTestTestTestTest2 as TestTestTestTestTestTest1,,  # Some really long comment bla bla bla bla bla
)

```

As you can see, there's a double comma at the end of the line resulting in syntax error. 

**Expected result:**
```
from .test import (
    TestTestTestTestTestTest2 as TestTestTestTestTestTest1,  # Some really long comment bla bla bla bla bla
)
```
Single comma should be present

**Comment by timothycrosley** [comment]
Thank you for reporting this issue! It has been fixed in develop with additional regression tests added and will be released before the end of the month / year.

Thanks!

~Timothy
