### ISSUE TITLE
pre-commit --all-files ignores configuration

### ISSUE THREAD

**Issue by neutrinoceros** [PyCQA/isort#1623]
Hi,
running `isort`'s pre-commit hook with the `--all-files` flag fails to take into account the project-configuration defined in `pyproject.toml` under `[tool.isort]`

This is the error I'm getting
```
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

$HOME/.cache/pre-commit/repo37ea6zim/py_env-python3.8/lib/python3.8/site-packages/isort/settings.py:411: 
UserWarning: Found <PROJECT_PATH>/pyproject.toml with [tool.isort] section, but toml package is not installed.
To configure isort with <PROJECT_PATH>/pyproject.toml, install with 'isort[pyproject]'.
```

I don't think this error message is meant to be triggered from the pre-commit hook as there's no way (that I'm aware of) to install `toml` in isolation along side the hook.

Related: I discovered this while trying to setup `pre-commit.ci` (https://pre-commit.ci) for repos using isort as a pre-commit hook. This tool runs `pre-commit --all-files` on pull requests so it's important that the configuration is taken into account, especially in that skipped files remain skipped. I also want to point that I couldn't understand from the documentation wether I should use `skip=` or `skip_glob=` here (the latter's doc is unclear).

**Comment by MarcoGorelli** [comment]
you might want to add
```
additional_dependencies: [toml]
```

**Comment by neutrinoceros** [comment]
Thanks a lot, this solves my problem ! Pardon me for misinterpreting the source of error.
