### ISSUE TITLE
force_sort_within_sections is not case-insensitive

### ISSUE THREAD

**Issue by gofr** [PyCQA/isort#1624]
I want my from-imports and straight-imports to be sorted together so I'd like to use `--force-sort-within-sections`. And I want my modules to be sorted case-insensitively too, which is already the default.

Sort the following with the `--force-sort-within-sections` flag:

    import a
    from Z import b, C

With a bash command that's: `echo -e 'import a\nfrom Z import b, C' | isort - --force-sort-within-sections`

### Expected result

    import a
    from Z import C, b

### Actual result

    from Z import C, b
    import a

The [`sorting.section_key`](https://github.com/PyCQA/isort/blob/8e6d383064d337813a5b021bd597e166ccd630b3/isort/sorting.py#L54) function that gets called doesn't care about the `case_sensitive` setting. It _does_ however get `order_by_type` passed in as a parameter and that lowercases the line if it's turned off. So if I call it like this: 

    echo -e 'import a\nfrom Z import b, C' | isort - --force-sort-within-sections --dont-order-by-type

I get:

    import a
    from Z import b, C

But that's still not what I want, because I _do_ want to order by type.

I see the `order_by_type` was added in 1372970. And I also see there's already a unit test covering this: https://github.com/PyCQA/isort/blob/6e5414cb72ee822d351968626bb9a37e10425857/tests/unit/test_isort.py#L2358

Is this a deliberate choice or an oversight? Should there be some code in there that lowercases just the module names (depending on `case_sensitive`)? And should `order_by_type` only lowercase the imported names, so it doesn't affect the module order?

**Comment by timothycrosley** [comment]
Closing as this was fixed via your PR, thank you!
