### ISSUE TITLE
Isort breaks on future imports when submodule imports are present

### ISSUE THREAD

**Issue by mwfrojdman** [PyCQA/isort#1637]
Version: 5.6.4
Python 3.9

**Description**
Isort moves other imports in front of `from __future__` leading to syntax errors when submodule imports are used

**Steps to reproduce**
Seems any module with a submodule import sorts before `__future__`.
`test.py`:
```
from __future__ import annotations
from .module import member
```

```
isort --atomic test.py 
/usr/lib/python3.9/site-packages/isort/api.py:362: UserWarning: /.../test.py unable to sort due to existing syntax errors
  warn(f"{actual_file_path} unable to sort due to existing syntax errors")
```
Resulting file (without `--atomic`):
```
from .module import member
from __future__ import annotations
```

**Comment by timothycrosley** [comment]
This is not the default behaviour of isort, which produces (correctly):

```python
from __future__ import annotations

from .module import member
```

Against the given file. Making wonder if it's the result of a config or a more complex example then given?

Can you provide the output of `isort test.py --show-config` and confirm test.py is a complete confirmed example and not a redacted one from a more complex production code snippet?

Thanks!

~Timothy

**Comment by mwfrojdman** [comment]
Hi,
you're right, we have an old `.isort.cfg` and turns out this combination of options triggers the behavior:
```
no_sections = true
sections = STDLIB, THIRDPARTY, FIRSTPARTY, LOCALFOLDER
```
So `sections` missing `FUTURE` was probably the issue. Curiously without the `no_sections: true` option the error doesn't occur.

I don't know if being able to disable `FUTURE` from sections makes sense - `__future__` imports always have to come first or it's a syntax error.

**Comment by diagonalDave** [comment]
Hi, 
I have found the same issue, although the config includes future in 'sections' see attached log. 
Any pointers would be appreciated, 
Thanks,
Dave

[isort.log](https://github.com/PyCQA/isort/files/5969884/isort.log)
[isort_test_example.py.txt](https://github.com/PyCQA/isort/files/5969886/isort_test_example.py.txt)

**Comment by timothycrosley** [comment]
@diagonalDave, is the isort_text_example the output or the input? If it's the output it seems correct, `future != __future__`, you could add another section and move it run under `__future__` if you wanted though - if so, see the guide here: https://pycqa.github.io/isort/docs/configuration/custom_sections_and_ordering/
