### ISSUE TITLE
README: How to use isort with pre-commit.com?

### ISSUE THREAD

**Issue by guettli** [PyCQA/isort#1639]
Thank you for isort!

It would be very kind, if you could explain (or maybe even advertise) how to use isort with [pre-commit.com](//pre-commit.com).

Thank you!

**Comment by MarcoGorelli** [comment]
Hi @guettli - did you check https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/#isort-pre-commit-step ?

**Comment by guettli** [comment]
@MarcoGorelli thank you, that's great. If I were you, I would put this on the top of the README

**Comment by timothycrosley** [comment]
Hi @guettli,

Thanks for the suggestion! I've added a link to the pre-commit documentation to the home page:

![isort_precommit_homepage](https://user-images.githubusercontent.com/2090154/106400911-1b790800-63d6-11eb-9b29-f1ed62934262.png)

Which links to a dedicated documentation page that will evolve over time, here: https://pycqa.github.io/isort/docs/configuration/pre-commit/
