### ISSUE TITLE
Settings Path affects sort results

### ISSUE THREAD

**Issue by RabbitRu** [PyCQA/isort#1643]
I'm trying to set up isort for CI\CD usage and use a single config file for all projects, but isort behaves differently when I specify ---sp compared to when I place .isort.cfg in project folder.
I'm using isort 5.7.0.

I created a little project to demonstrate the problem https://github.com/RabbitRu/isort_issue
Project tree:
```
├── project_folder
│   ├── .isort.cfg
│   ├── src
│   │   └── base.py
│   └── test.py
└── settings_folder
    └── .isort.cfg
```
.isort.cfg files are equal

If isort is executed from project_folder with simple command  `isort .` I get the expected behaviour:
```
# Standard Library
import json

# Third Party
from tqdm import tqdm

# Our Projects
from our_project import AnotherClass

# First Party
from src.base import BaseClass
```

But if .isort.cfg from settings_folder is passed and isort is executed as `isort . --sp ../settings_folder/.isort.cfg` the result is:
```
# Standard Library
import json

# Third Party
from src.base import BaseClass
from tqdm import tqdm

# Our Projects
from our_project import AnotherClass
```

I want local folders grouped to other section from third party packages, but I don't want to use relative imports (.src.base) nor I want to enumerate all possible local folders names in config (using known_localfolder in config).
Am I using isort wrong or is this a bug?

**Comment by timothycrosley** [comment]
The solution here is to explicitly define the source paths:

https://pycqa.github.io/isort/docs/configuration/options/#src-paths

The settings path is only used as a fallback if no source paths are defined (then it is assumed source is relative to the location of the config file). The src paths can also be set in the config file (in which case you set them relative to the location of the config file) or passed in from the command line itself.

**Comment by jack1902** [comment]
@timothycrosley you got a bad URL there

For anyone finding this in the future:

https://pycqa.github.io/isort/docs/configuration/options#src-paths
