### ISSUE TITLE
Feature Request: Lines Before Imports

### ISSUE THREAD

**Issue by Spectre5** [PyCQA/isort#1646]
There is already a `lines_after_imports` option.  Would it be possible to also have a `lines_before_imports` option?  I have a project where half of the files have a space after the module doc string and before the first import and the other half do not have a blank line.  Ideally isort could be used to make these consistent the same way it can to make the spacing after the imports consistent.

```
"""Module docstring."""

import os
```

```
"""Module docstring."""
import os
```

**Comment by sgaist** [comment]
Hi,

I'd like to take care of this one for Hacktoberfest.

**Comment by anirudnits** [comment]
@sgaist thanks :) assigned this issue to you.
