### ISSUE TITLE
Wrapped "as" imports with use_parentheses and multi_line_output=6 places closing parenthesis wrongly

### ISSUE THREAD

**Issue by gofr** [PyCQA/isort#1654]
I came across this while working on tests and fixes for #1640:

    echo 'from foo.bar.baz import aaaaa as bbb' | isort --line-length=20 --multi-line=6 --use-parentheses -

Expected output:

    from foo.bar.baz import (
        aaaaa as bbb
    )

Actual output:

    from foo.bar.baz import (
        aaaaa as bbb)

Caused by the following if condition missing mode 6 (VERTICAL_GRID_GROUPED_NO_COMMA):

https://github.com/PyCQA/isort/blob/8d6f0b994b0f1917d7c9a195be0b1fc2c17e7bf8/isort/wrap.py#L111

**Comment by gofr** [comment]
Easy to fix of course. If you do end up accepting #1653 that will already get rid of this problem.

**Comment by timothycrosley** [comment]
Closing as this is fixed in your merged PR: https://github.com/PyCQA/isort/pull/1653 and will make its way in the next release of isort :tada:
