### ISSUE TITLE
'isort -' adds a (colored?) character at the end of the pipe when the test is launched from PyCharm

### ISSUE THREAD

**Issue by mwouts** [PyCQA/isort#1657]
Hi there. Sorry this issue is quite hard to reproduce, and maybe not so specific to `isort`, but hopefully it might still help a few users if they ever find the same issue as I do.

So, when I run a test that pipes a Python file into `isort` (see the code below) I see a strange character `\x1b[0m` being appended to the output:
```
>       assert out.decode("utf-8") == text
E       AssertionError: assert 'import numpy as np\n\x1b[0m' == 'import numpy as np\n'
```

The issue is there only if I run the test in PyCharm. I don't get any error
- if I run the test at the CLI: `pytest tests/test_pipe_isort.py`
- or if I replace `isort` with `black` in the test.

I don't think the issue was there in the past - but I run the CLI version of the tests more often than the interactive version. Also I tried downgrading `isort` to `5.6.4` but that did not fix it.

Do you have any clue where this colored character might come from? (If no, feel free to close this issue, I'll just add a comment to my test to let the user know that the test should be run at the CLI).

This is the content of `test_pipe_isort.py`:
```
import subprocess


def test_pipe_isort():
    text = "import numpy as np\n"

    command = ["isort", "-"]
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stdin=subprocess.PIPE)

    out, err = process.communicate(input=text.encode("utf-8"))
    assert out.decode("utf-8") == text
```

Also, I am running the tests in an environment created with
```
conda env create --file environment.yml
```
using this [environment.yml](https://github.com/mwouts/jupytext/blob/master/environment.yml) file.

**Comment by gofr** [comment]
isort does have support for outputting colored text, but if I'm not mistaken it only does that if you have `colorama` installed (which I don't see in your environment.yml) and use the `--color` flag. So I don't think isort is doing this in your case.

The `\x1b[0m` you're seeing is the ["reset" ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters). [PyCharm supports ANSI escape codes](https://youtrack.jetbrains.com/issue/PY-1925). I imagine PyCharm might be outputting the reset character to avoid the commands you run potentially messing up its console. And this isn't interacting well with `subprocess` in some way.

This PyCharm bug looks very related: https://youtrack.jetbrains.com/issue/PY-44236

**Comment by mwouts** [comment]
Thanks you @gofr for the links, very instructive! So yes sure clearly this is caused by PyCharm, I will follow the issue tracker there. Thank you again for your help!
