### ISSUE TITLE
Add option to disable force_sort_within_sections for relative imports

### ISSUE THREAD

**Issue by jwodder** [PyCQA/isort#1659]
It appears to be isort's opinion that statements of the form "`from . import foo`" are "straight-style" imports (like `import pathlib`) rather than "from-style" imports (like `from pathlib import Path`).  As a result, when `force_sort_within_sections` is in effect, these statements get sorted among "`from .foo import bar`" statements as though they were written "`from .import import foo`".  I don't like this; I would like to have my `force_sort_within_sections` and eat it, too.

Specifically, my goal is for isort to sort the following statements as shown:

```python
import arithmetic
from botany import flower
import chemistry

from . import foo
from .apple import bar
from .banana import baz
from .. import quux
from ..asparagus import gnusto
from ..broccoli import cleesh
```

I can get the relative imports to be sorted the way I want by setting `reverse_relative = true`, but then I also need to set `force_sort_within_sections = true` in order to get the absolute imports to sort the way I want, and that ends up changing the ordering of the relative imports.  I would thus like to request a configuration option or setting for achieving the above ordering, such as by making `force_sort_within_sections` not apply to relative imports.

**Comment by gofr** [comment]
It's even more instructive if you replace `banana` by `mango` (or any other fruit that sorts alphabetically after `import` :wink:) in that example. Then with `force_sort_within_sections = true` they get sorted like this:

    from .apple import bar
    from . import foo
    from .mango import baz

That's definitely not right.

**Comment by timothycrosley** [comment]
Closing this as it is fixed by @gofr's pr here https://github.com/PyCQA/isort/pull/1664 and the addition of the `sort_relative_in_force_sorted_sections` option
