### ISSUE TITLE
Specifying profile=black in settings behaves differently than --profile=black

### ISSUE THREAD

**Issue by benjschiller** [PyCQA/isort#1660]
It seems that when you specify the settings path via --sp (which is what github's super-linter does), then isort also changes the directory and src_paths. the result is that it treats the code within your repo as a third-party dependency and wants to rearrange the imports. i figured out the difference using the --show-config option

this is with version 5.7.0

**Comment by timothycrosley** [comment]
While this is technically true, i think isort is doing the right thing here. isort needs some way of explicitly knowing where your project starts and ends, one of those ways is the settings file location if it exists. You can also update that settings file to point to whichever source paths you would like.

**Comment by timothycrosley** [comment]
I think even more importantly, it's not that setting profile=black, in any way behaves differently than --profile=black, they behave identically. It's that have a settings file behaves differently than not having a settings file. And this is true for many CLI tools.
