### ISSUE TITLE
Multiple runs of isort keep adding lines when using import_heading_stdlib

### ISSUE THREAD

**Issue by JohnVillalovos** [PyCQA/isort#1670]
Have the following file:

```
#!/usr/bin/python3 -ttu
# Standard Library
import argparse
import datetime

import attr
import requests


def foo() -> int:
    print("Hello world")
    return 0


def spam():


    # Standard Library
    import collections
    import logging
```

Config of:
`import_heading_stdlib = Standard Library`

Each run of isort will add a new blank line in the function `spam()` between `def spam` and `# Standard Library`

**Comment by timothycrosley** [comment]
Hi @JohnVillalovos,

Thanks for reporting this issue! Is there any other configuration options set? As you can see in the added test file, standard settings + the header do not seem to trigger this issue.

Thanks!

~Timothy

**Comment by JohnVillalovos** [comment]
I was using isort VERSION 5.0.3 in my failing test.

When I upgraded to VERSION 5.7.0 it worked without problems.

Sorry about that 😟
