### ISSUE TITLE
different results when running isort

### ISSUE THREAD

**Issue by aabramovrepo** [PyCQA/isort#1678]
Hi All,

   I'm facing one issue running `isort`. My project has the following structure:

```
project
├── src
│   ├── ...
│   └── ...
├── src_py
│   ├── setup.cfg
│   └── tests
└── <other stuff>
    ├── ...
    └── ...
```

running `isort` in the main project directory and in `src_py ` leads to different results somehow. I'm using standard `isort `settings and do not have an `isort `config file or `[isort]` section in `setup.cfg`. Apparently `isort` is using different settings, so the output of `isort --show-config` looks different at both places. What might be the reason for this and what is the best workaround?

Thanks in advance for your help!

Best,
Alexey

**Comment by timothycrosley** [comment]
isort needs some way to know where your project starts and ends to be able to correctly identify imports, the easiest way to do this is to add a an isort config at the root of your project, otherwise you need to always run isort from the same location, or always explicity specify the src paths relative to where it is ran.

**Comment by aabramovrepo** [comment]
@timothycrosley thanks for your response and the hint! I have created `.isort.cfg` file in `src_py/` and specified all directories I wanna check with `isort` there in `src_paths`. This way `isort` runs in the same manner while being triggered from both `project` and `src_py`. Is this the way to go in case I don't want to move `.isort.cfg` to the `project` directory?

**Comment by timothycrosley** [comment]
Yes that's right!
