### ISSUE TITLE
`extend_skip` option to skip files *in addition to* files skipped in `skip`

### ISSUE THREAD

**Issue by jack1142** [PyCQA/isort#1684]
This option would behave like `skip`, but it would add the files specified in `extend_skip` on top of the ones skipped by `skip`. I'm guessing that this would most commonly be useful to not have to include the defaults in `skip` option in isort configuration file *when* you just want to skip some path in addition to the (imo) useful defaults.
In some environments, it could probably also be useful to pass `--extend-skip` cli flag to add onto `skip` that's *already* included in the isort configuration file. I guess that one would be a bit limited considering that one would probably often already use `extend_skip` in the configuration and the cli flag would override that, but I'm guessing that at least some would probably be able to work with that anyway.

Here are some tools that already allow this in case that helps :)
[flake8](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-extend-exclude)
[black](https://github.com/psf/black/commit/beecd6fd0a9103aa91b1019dcf8fc774b667ea6c)

**Comment by jack1142** [comment]
Update: I guess the existing `skip_glob` might already be enough for this considering it already extends `skip`. I don't think I'm gonna need this in such case then and I leave it up to you whether this should be closed or not.

**Comment by timothycrosley** [comment]
Hi @jack1142, 

Thanks for bringing this up! I think it makes sense for isort to have an extend skip to stay as CLI compatible with other tools as possible. I've added both an extend skip and extend skip glob flag to address this. 

Thanks!

~Timothy

**Comment by govindrai** [comment]
Could you guys explain extend_skip? Even after reading the docs I don't understand what it's purpose is
