### ISSUE TITLE
force_single_line not forcing single line

### ISSUE THREAD

**Issue by Inveracity** [PyCQA/isort#1687]
Heya, I'm experiencing an issue where `force_single_line` is not being forced

My tox config file looks like this:
```yaml
#tox.ini
[isort]
profile=google
src_paths=myproject
force_single_line=True
line_length=150
```

This is the result of running `isort .`

This was my expectation:
```python
from typing import List
from typing import NoReturn
```

But this is the result
```python
from typing import List, NoReturn
```

I also tried running it with `--force-single-line-imports`

Versions:
- isort 5.7.0
- Python 3.9.2

**Comment by gofr** [comment]
The `google` profile specifically excludes the `typing` module from this behavior: https://pycqa.github.io/isort/docs/configuration/profiles/#google

If you want to override this, you can set [the `single_line_exclusions` option](https://pycqa.github.io/isort/docs/configuration/options/#single-line-exclusions) in your config.

**Comment by Inveracity** [comment]
aha! Thank you 👍
