### ISSUE TITLE
isort deletes lines with a typo

### ISSUE THREAD

**Issue by bersbersbers** [PyCQA/isort#1688]
`isort` 5.7.0 invoked with
```
printf "from package1 import alright\nfrom package2 imprt and_its_gone\nfrom package3 import also_ok" | isort -
```
outputs
```
from package1 import alright
from package3 import also_ok
```
The second line is missing.

**Comment by gofr** [comment]
What would you like `isort` to do in this case?

I think this probably happens with all lines that start with one of these strings and then later turn out to be invalid import statements:
https://github.com/PyCQA/isort/blob/f76ed04404ed7e814237564297d7b5e1f3358654/isort/core.py#L15

I can think of many ways to handle this. For example fix the typo, treat the line as an import and sort it somehow anyway, or treat the line as a non-import and move it down. But I think the simplest and most useful thing here is to use the [`atomic`](https://pycqa.github.io/isort/docs/configuration/options/#atomic) option, so `isort` exits with a syntax error.

**Comment by bersbersbers** [comment]
Thank you - `--atomic` is somewhat helpful in my use case (VS Code), although it triggers a notification that is not auto-dismissed when the error is corrected. That is something for VS Code to consider, I guess.

For the other question, consider VS Code with default settings as a use case (https://code.visualstudio.com/docs/python/editing). Unless I am mistaken, it auto-sorts on each save, so a typo should not be uncommon for `isort` to see. Clearly, the line should not be deleted, as I have just typed it. On the other hand, sorting the line someplace else (out of view, potentially) is not ideal, either, but there's still a linter to detect that.

I think for the sake of consistency, you could do the same thing you do when you hit a line that is not detected as an import at all (`frm package import something`) -  these currently stay in place and sometimes are separated from the rest by an extra line break, which I think is a good solution:

`printf "from package1 import alright\nfrm package2 import and_its_gone\nfrom package3 import also_ok" | isort -`:

```
from package1 import alright

frm package2 import and_its_gone
from package3 import also_ok
```
