### ISSUE TITLE
Support for PEP 582 (Python local packages directory)

### ISSUE THREAD

**Issue by ntninja** [PyCQA/isort#1697]
When using flake8 for projects managed with [PDM](https://pdm.fming.dev), which implements PEP 582 (Python local packages directory), I find a large amount of errors reported for files under the local packages directory like this:

```
ERROR: /home/alexander/src/flake8-tabs/__pypackages__/3.9/bin/isort-3.9 Imports are incorrectly sorted and/or formatted.
--- /home/alexander/src/flake8-tabs/__pypackages__/3.9/bin/isort-3.9:before   2021-03-24 20:41:20.224279
+++ /home/alexander/src/flake8-tabs/__pypackages__/3.9/bin/isort-3.9:after 2021-03-24 21:15:49.689383
@@ -2,7 +2,10 @@
 # -*- coding: utf-8 -*-
 import re
 import sys
+
 from isort.main import main
+
+
 if __name__ == '__main__':
     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
     sys.exit(main())
```

While the `__pypackages__` directory is specified by the recent PEP-582, that PEP is currently draft status, so the name (and the entire feature) is guaranteed to stick around. Although PDM and PyFlow already use this convention and provide PEP-582 shims, they'd probably change if the PEP proves unworkable for some reason.

FYI, `flake8` decided to close a similar request at [GL/pycqa/flake8#681](https://gitlab.com/pycqa/flake8/-/issues/681) noting that “we'll maybe reconsider this if [PEP-582] is accepted”.

**Comment by ntninja** [comment]
For anybody finding this, workaround is to put the following into your config:

```
skip_glob = [
	"__pypackages__/**",
]
```

**Comment by timothycrosley** [comment]
I'd be very surprised if any significant number of projects legitimately want Python imports inside of a __pypackages__ directory sorted, and would be inconvenienced  by a change to include it by default. I'd be happy to add this exclude by default to isort, I might suggest filing an issue with black as well as the 2 tools are often utilized together: https://github.com/psf/black/issues?q=is%3Aissue+PEP+582+is%3Aopen

**Comment by timothycrosley** [comment]
This is implemented in develop and will be pushed to PyPI in the 5.9.0 release of isort

**Comment by ntninja** [comment]
Thank you!

I won't submit this to black through since I don't use and dislike for “your not ready to embrace back” reasons. Somebody else will have to do that.
