### ISSUE TITLE
`Black` and `isort` incompatibility with `pre-commit`

### ISSUE THREAD

**Issue by ehontoria** [PyCQA/isort#1702]
# The problem
According to the documentation (https://pycqa.github.io/isort/docs/configuration/black_compatibility/) in order to get a `pre-commit` configuration that works with both `black` and `isort` I just need to add a couple arguments.

After setting that up though I'm seeing a discrepancy where `black` and `isort` can't seem to agree on what to do with the following line:

# Black output
```
from datascience_shared.export_pipeline.abstract_exports import (
    ExportBase,
    ExtractorBase,
)
```

# isort output
```
from datascience_shared.export_pipeline.abstract_exports import ExportBase, ExtractorBase
```

# Configuration and environment
The relevant pieces of my `pre-commit` configuration:
```
repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
        -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
        -   id: isort
            args: ["--profile", "black", "--filter-files"]
            language_version: python3
```
Python version: 2.7.15
`pre-commit` version: 1.21.0 (the latest version compatible with py2)
`isort` version (from the config): 5.6.4
`black` version (from the config): 20.8b1

Seems to be the same problem as https://github.com/PyCQA/isort/issues/1388 except on isort 5.

**Comment by ehontoria** [comment]
It looks like if I add the recommended `pyproject.toml` it works - the wording should be updated for that file to be "required" not "recommended".

**Comment by timothycrosley** [comment]
Hi @ehontoria,

I'm sorry if you ran into an problem! I think something is missing in this issue however, I went ahead and made a test repo to verify:

https://github.com/timothycrosley/isort_pre_commit_test_issue_1702

- isort works using pre-commit + black with only the config and example given both for commit and running pre-commit against all files.
- This even extends to it working on pre-commit.ci.

Is it possible you expected isort to work in some other context (such as inside an editor integration, or direct from CLI) based on the pre-commit config? If so, I don't think this is ever the case for any utility. And yes, a dedicated config would be needed in that case, and in fact the pre-commit setting of the black profile could then be removed.
