### ISSUE TITLE
CLI option --multi-line does not work

### ISSUE THREAD

**Issue by gorsil** [PyCQA/isort#1707]
--multi-line does not work no matter what. I've tried all sorts of arguments, both numeric and string aliases, no success (examples below)
python version - 3.9.2
isort version - 5.8.0
<details>
<summary>Examples</summary>

```
isort -m 1 test.py --diff
--- /home/gorsil/projects/test.py:before	2021-04-17 15:30:10.626664
+++ /home/gorsil/projects/test.py:after	2021-04-17 15:30:54.973651
@@ -1,9 +1,2 @@
-from datetime import (
-    datetime,
-    time,
-)
-from typing import (
-    Any,
-    Iterable,
-    Tuple,
-)
+from datetime import datetime, time
+from typing import Any, Iterable, Tuple

isort -m 3 test.py --diff
--- /home/gorsil/projects/test.py:before	2021-04-17 15:30:10.626664
+++ /home/gorsil/projects/test.py:after	2021-04-17 15:31:04.072208
@@ -1,9 +1,2 @@
-from datetime import (
-    datetime,
-    time,
-)
-from typing import (
-    Any,
-    Iterable,
-    Tuple,
-)
+from datetime import datetime, time
+from typing import Any, Iterable, Tuple

isort -m VERTICAL_HANGING_INDENT test.py --diff
--- /home/gorsil/projects/test.py:before	2021-04-17 15:30:10.626664
+++ /home/gorsil/projects/test.py:after	2021-04-17 15:31:25.138409
@@ -1,9 +1,2 @@
-from datetime import (
-    datetime,
-    time,
-)
-from typing import (
-    Any,
-    Iterable,
-    Tuple,
-)
+from datetime import datetime, time
+from typing import Any, Iterable, Tuple

isort -m HANGING_INDENT_WITH_PARENTHESES test.py --diff
--- /home/gorsil/projects/test.py:before	2021-04-17 15:30:10.626664
+++ /home/gorsil/projects/test.py:after	2021-04-17 15:31:37.027268
@@ -1,9 +1,2 @@
-from datetime import (
-    datetime,
-    time,
-)
-from typing import (
-    Any,
-    Iterable,
-    Tuple,
-)
+from datetime import datetime, time
+from typing import Any, Iterable, Tuple
```
</details>

**Comment by timothycrosley** [comment]
Hi @gorsil,

I could see why this would be confusing and frustrating! By default isort doesn't apply the multi-line grid wrap mode until the length of the line is above the set line limit. If you want it to always be enforced use the --force-grid-wrap flag (see: https://pycqa.github.io/isort/docs/configuration/options/#force-grid-wrap)

I hope this is helpful!

~Timothy

**Comment by gorsil** [comment]
@timothycrosley  Oh, I see now. Thank you for the explanation!

**Comment by gorsil** [comment]
@timothycrosley Oh, I see now. Thank you for the explanation!
I guess this calls for a documentation update of some sort. I've spent good 30-40 minutes trying to figure this out on my own, unsuccessfully. Being unfamiliar with the projects terminology I've looked for some sort of "multi line" reference
