### ISSUE TITLE
UserWarnings: "Likely recursive symlink detected" and "X was skipped as it's listed in ..."

### ISSUE THREAD

**Issue by RuRo** [PyCQA/isort#1709]
This issue is about 2 `UserWarning`s. The first one seems to be a false-positive, the second one IMO should be a print instead of a warning.

1) [This line](https://github.com/PyCQA/isort/blob/99faae897f9da95cfd74ef9914c70313ed9abac3/isort/files.py#L30) in `isort/files.py` is possibly wrong as it seems to be triggered by any valid symlink, not only recursive ones. Now that I'm thinking about it, is there actually any reason to give such a warning even if this code did what it says it does and detected recursive symlinks? Why is a recursive symlink considered an exceptional condition if it's clearly supported by the very code that's giving the warning?

2) [This line](https://github.com/PyCQA/isort/blob/99faae897f9da95cfd74ef9914c70313ed9abac3/isort/main.py#L1182) in `isort/main.py` reports the skipped files as warnings (if the `--verbose` setting is enabled). I would argue that this should be a regular print. It's skipping a file, because it was specified to be skipped by the user. Therefore, it's an informational message, not a warning. It should go to `stdout` instead of `stderr` and it shouldn't be formatted as a warning (i.e. the user shouldn't care which line in which source file of `isort` this message was triggered).
   
   There is already a precedent for `print`ing informational messages if `--verbose` is specified. For example, [this line](https://github.com/PyCQA/isort/blob/f074239e5e39c2dd9e4d373e3c6ce528dae3f78c/isort/parse.py#L437) and [this line](https://github.com/PyCQA/isort/blob/f074239e5e39c2dd9e4d373e3c6ce528dae3f78c/isort/deprecated/finders.py#L393) (the second one is arguably a better candidate to be a warning actually)

I would be willing to create a PR that removes the first warning and/or changes the second warning to a print, if you agree with the above changes.

**Comment by timothycrosley** [comment]
I agree with the overall changes suggested here and would gladly merge a PR that implements them!

>  Now that I'm thinking about it, is there actually any reason to give such a warning even if this code did what it says it does and detected recursive symlinks? Why is a recursive symlink considered an exceptional condition if it's clearly supported by the very code that's giving the warning?

I think there is almost never a good or intentional reason to have a recursive symlink, and the presence of one tends to break many especially newer, CLI tools. So I can certainly see how that message could be useful - on the other hand, it's not really isort's job to alert users of general code hygiene issues outside of imports - so I'm happy to just have it fully removed.

Thanks!

~Timothy
