### ISSUE TITLE
"fatal: not a git repository: '.git'" if skip_gitignore and GIT_DIR are set

### ISSUE THREAD

**Issue by torfsen** [PyCQA/isort#1713]
Background: I'm trying to run isort as part of a Git `pre-commit` hook. I know about the option of using isort with the [pre-commit project](https://pre-commit.com/) and about using [isort's native git hook support](https://pycqa.github.io/isort/docs/configuration/git_hook/). However, both of these are not applicable in my personal use case.

I have `skip_gitignore` set to `true` in my `pyproject.toml`. Normally that works fine:

```
$ isort .
Skipped 4 files
```

However, when I run the same command via a custom `.git/hooks/pre-commit` Bash script, then I get the following output:

```
$ git commit
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
Skipped 4 files
```

I can replicate this behavior by setting the `GIT_DIR` environment variable before calling `isort`:

```
$ GIT_DIR=.git isort .
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
fatal: not a git repository: '.git'
Skipped 4 files
```

My `pyproject.toml`:

```
$ cat pyproject.toml 
[tool.isort]
skip_gitignore = true
```

If I disable `skip_gitignore` then those messages go away.

This is on isort 5.8.0 and Python 3.6.13.

**Comment by timothycrosley** [comment]
I have been unable to reproduce this, however, I will say, this is a combination that should never be needed as precommit already ignores git ignored files.

**Comment by arthurio** [comment]
Actually, it seems that even though the error messages are displayed, `isort` is still able to do its job... So it's more of an esthetic issue than a functional one ¯\_(ツ)_/¯
