### ISSUE TITLE
Line break and tab indentation makes wrong fix

### ISSUE THREAD

**Issue by PicoSushi** [PyCQA/isort#1714]
`isort` causes odd fixing with import line which contains line berak and tab indentation.

before `isort` (Notice that this code uses Tab indentation, not spaces.)

```py
from sys \
	import version
print(version)
```

after `isort`
```py
from sys import importversion

print(version)
```

expected
```py
from sys import version

print(version)
```

### Versions
- macOS Big Sur 11.2.3
- Python 3.9.4
- isort 5.7.0

**Comment by anirudnits** [comment]
This problem persists with the current 5.8.0 version as well.
