### ISSUE TITLE
Sublime plugin repo is 404'd

### ISSUE THREAD

**Issue by sricks** [PyCQA/isort#1715]
Hello, I hope this issue is helpful. This page:

https://github.com/pycqa/isort/wiki/isort-Plugins

references this repo which no longer exists:
https://github.com/jcugat/sublime-text-isort-plugin#install

It looks like the original plugin repo that one was forked from still exists, but hasn't been updated in 6 years: https://github.com/thijsdezoete/sublime-text-isort-plugin

There's also a plugin in Sublime's PackageControl which was updated 2 years ago, and which is the one I'm using now: https://packagecontrol.io/packages/isort

It does work, but doesn't seem to pick up the settings from either a project's `pyproject.toml` or `.isort.cfg` or even `~/.isort.cfg` so it's not really usable.

I'm not clear if that's an issue with the plugin or with isort but I assume it's on the plugin side. I'm very busy at a new job but maybe I can maintain the sublime plugin in the future since it seems the one in PackageControl is also abandoned.

**Comment by timothycrosley** [comment]
I'd love to see an updated sublime plugin! For now I've updated the wiki to point to the slighly newer plugin you listed here to at least resolve the 404 error.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Closing as this issue as the 404 is fixed, but I look forward to any updates on a newer plugin.
