### ISSUE TITLE
Add config for double blank lines after imports

### ISSUE THREAD

**Issue by janosh** [PyCQA/isort#1719]
I would appreciate an option that leaves two blank lines between imports and code:

```py
import numpy as np


np.zeros(5)
```

**Comment by anirudnits** [comment]
Hello @janosh, have you looked at the `lines-after-import` option by which you can specify the number of newlines after an import section. For your particular use-case, you could specify `lines-after-import` as 2 and get the desired output.

However, this flag won't cover the case where the code section is above the import section such as 
``` python
print(sys.path)
import pandas as pd
```  
and this has already been raised in #1646.

Hope this helps.

**Comment by janosh** [comment]
Oops, my bad for not reading the docs properly.
