### ISSUE TITLE
isort drops noqa comments when on multiple import lines

### ISSUE THREAD

**Issue by levsa** [PyCQA/isort#1721]
pyproject.toml
```
[tool.isort]
profile = "black"
force_single_line = true
```

main.py
```
from some_very_long_filename_to_import_from_that_causes_a_too_long_import_row import (  # noqa: E501
    CONSTANT_1,
)
from some_very_long_filename_to_import_from_that_causes_a_too_long_import_row import (  # noqa: E501
    CONSTANT_2,
)
```

Running `isort main.py` drops `# noqa: E501` on the second import line. Same bug without "black" profile.

With isort 5.8.0

**Comment by timothycrosley** [comment]
Thanks for reporting this issue! I'm sorry this affected you! it is now fixed in develop and will be pushed to PyPI in the next release of isort.
