### ISSUE TITLE
how to prevent isort from sorting subfolders

### ISSUE THREAD

**Issue by epogrebnyak** [PyCQA/isort#1724]
Many thanks for supporting isort!

I run into a curious issue: when running isort over a a folder where there was an environment subfolder `.env` and isort picked up sorting the imports in all the installed packages, which resulted in further error.

When I run ```black .``` the formatting affects just .py files in my project, does not affect files form .gitignore.

When I run ```isort .``` the changes affect everything in subfolders. How do I prevent this behavior? I studied documentation and `isort --help`, but could not think of a good option.

So far I resort to `isort specific_file.py`

**Comment by ucodery** [comment]
Hi @epogrebnyak, the documentation can be a little intimidating at first read. Have you seen this section https://pycqa.github.io/isort/docs/configuration/options/?  There are a few configuration skip settings that could help you, notably `extend_skip` can be provided with directory names. Also `skip_gitignore` can be set to true (false by default) which sounds like it might be the easier fix for your specific situation as `black` is not needing extra exclude options.

**Comment by epogrebnyak** [comment]
> 
> 
> Hi @epogrebnyak, the documentation can be a little intimidating at first read. Have you seen this section https://pycqa.github.io/isort/docs/configuration/options/? There are a few configuration skip settings that could help you, notably `extend_skip` can be provided with directory names. Also `skip_gitignore` can be set to true (false by default) which sounds like it might be the easier fix for your specific situation as `black` is not needing extra exclude options.

Thanks for the guidance! I'm currently doing `isort . --check-only --skip-glob .*`, where `.*` is a pattern for hidden directory like `.env` , etc `.venv`. Maybe there is other way to configure it too. 

As a subbestion - cansimilar skpping pattern be incorporated to isort default as in black? A lot of people use two tools together, reasonable to extect similar behaviour. I can try dig into configuration for black default if anyone endorses that.

**Comment by ucodery** [comment]
Glad that worked! `.*` is a great pattern for skipping, I'll just note that  using `--skip-glob` will make isort only skip what you specified, while `--extend-skip-glob` will add your pattern to other files already ignored by isort. isort has quite a few skips by default; from the docs `(.bzr, .direnv, .eggs, .git, .hg, .mypy_cache, .nox, .pants.d, .svn, .tox, .venv, _build, buck-out, build, dist, node_modules, venv)` that's pretty nice!

Again, I'll note that the option `--skip-gitignore` will use your `.gitignore` just like black does by default. You can run `isort <your options here> --show-files ./` to see all the files isort thinks it needs to read, without modifying them. This can maybe help you find the right combination of options (careful, this can be verbose!). You could compare with `black --check --verbose` but the output won't be one-to-one.

Black by default excludes these paths `(.git, .hg, .mypy_cache, .nox, .tox, .venv, _build, buck-out, build, dist)` actually less than isort! The difference is that using `.gitignore` is default for black, but opt-in for isort.

As an action item from this @timothycrosley probably if an isort-black inter-op doc is ever created (#1518) there should be mention that `--skip-gitignore` should be used to get both tools checking the same files. (and how to not clobber this ignore by using e.g. --skip later on)
