### ISSUE TITLE
Get symlink warning when even when --dont-follow-links

### ISSUE THREAD

**Issue by magicl** [PyCQA/isort#1728]
Using 5.8.0, with --dont-follow-links, I still get this warning: Likely recursive symlink detected

**Comment by timothycrosley** [comment]
Hi @magicl,

Thanks for reporting this issue, and I'm sorry you are experiencing it! This should be fixed now in the develop branch and released in 5.9.0 later this month.

~Timothy

**Comment by timothycrosley** [comment]
Closing now as 5.9 has been released, sorry for the delay here!
