### ISSUE TITLE
Compatibility with flake8 appnexus

### ISSUE THREAD

**Issue by toby-coleman** [PyCQA/isort#1730]
I have a project that uses flake8 with the `appnexus` setting for ordering imports:
```ini
[flake8]
ignore = E501, E226, E121, E123, E126, E24, E704, E122, E127, E128, W504, E731, W605, F541, E741, F821, E203, W503
max-line-length = 100
count = True
show_source = True
statistics = True
import-order-style = appnexus
```

Following the discussion in #1395 I am using the following configuration in `pyproject.toml` to configure isort. In particular I am setting `reverse_relative` to get the relative imports ordered correctly.
```ini
[tool.isort]
profile = "black"
multi_line_output = 3
force_grid_wrap = 0
wrap_length = 100
line_length = 100
use_parentheses = true
include_trailing_comma = true
force_sort_within_sections = true
lines_after_imports = 2
order_by_type = false
case_sensitive = false
reverse_relative = true
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","APPLICATION","LOCALFOLDER"]
no_lines_before = "LOCALFOLDER"
known_application = "my_package"
```

However, I still face problems with files containing the following combination of relative imports (ordered by isort):
```python
from .a import func_a
from . import b
```
where flake8/appnexus complains that
```
I100 Import statements are in the wrong order. 'from . import b' should be before 'from .a import func_a'
```

Is there a way to make isort fully compatible with appnexus in this situation?

**Comment by gofr** [comment]
I think this is the same issue as #1659. You'll need to add the option I added there to fix it:
https://pycqa.github.io/isort/docs/configuration/options/#sort-relative-in-force-sorted-sections

**Comment by timothycrosley** [comment]
@gofr and @toby-coleman if we can ensure that is indeed the issue and is fixed by adding the appropriate option, let me know! I'd be happy to update the appnexus profile to use that option by default, with additional testing added.

Thanks!

~Timothy

**Comment by toby-coleman** [comment]
Thanks @gofr and @timothycrosley - setting `sort_relative_in_force_sorted_sections = true` was exactly what I needed.

Adding it to the appnexus profile sounds a great idea.
