### ISSUE TITLE
Feature Request: Footer Section

### ISSUE THREAD

**Issue by Spectre5** [PyCQA/isort#1733]
There is already a feature to add import headings at the start of a section.  Can we also add a footer at the end of the section?  My use case is where I've made a custom section for some libraries that are not available in the development environment and so I want to surround those imports with disable and enable tags to silence `pylint`.

Currently I just use the enable comment as the heading for the next section, but this is fragile as there are times where that section doesn't exist and thus the imports are disabled for the entire rest of the file.

As a quick example of what I'd like to have:

```python
import os

# pylint: disable=import-error
import library_not_available_in_dev

# pylint: enable=import-error

import first_party
```

Note that I've added a blank line before the line `# pylint: enable=import-error` for compatibility with `black` which doesn't allow a comment on a line directly after an import.

I realize that I could just use `import library_not_available_in_dev  # pylint: disable=import-error` on a single line instead, but in my actual application I have many of these libraries that are not available and thus it is cleaner/preferable to surround that block of imports with disable/enable tags as I've shown.

**Comment by timothycrosley** [comment]
I like this idea! And would happily merge in a PR that adds support - or circle back and complete it for a future version. Thanks for submitting the improvement ticket!

**Comment by Spectre5** [comment]
Great.  My personal life is busy at the moment, but if you don't get around to it soon, I'll submit a PR when I can find some time
