### ISSUE TITLE
isort removes some imports when a comment is used

### ISSUE THREAD

**Issue by adamsol** [PyCQA/isort#1741]
The issue seems to happen when a comment breaks the configured line length limit.

With this configuration:

```
[settings]
line_length = 50
multi_line_output = 2
```

a line like this (54 characters long):

```
from src import abcd, qwerty, efg, xyz  # some comment
```

is transformed to:

```
from src import abcd, efg      # some comment
```

**Comment by timothycrosley** [comment]
So sorry you experienced this! Thank you for reporting. This is the nastiest bug I've seen slip through in years. Was able to confirm with local testing - only saving grace is it only affects a few of the more rarely used wrap modes, and I can confirm all others are unaffected. I'll try to get a fix released soon!

**Comment by timothycrosley** [comment]
This is fixed in develop and will be released in the next version of isort, thanks again for reporting!
