### ISSUE TITLE
Can you release a new version on `PyPI` from the current master?

### ISSUE THREAD

**Issue by RuRo** [PyCQA/isort#1742]
@timothycrosley There are a couple merged but unreleased bug fixes currently just sitting in `main`, that I really want to finally apply in my projects (need a `PyPI` release to pin the version for `CI`). The last release was Mar 21, 2021, so it should be about time to make a new release anyway.

Pretty please.

**Comment by timothycrosley** [comment]
Hi @RuRo!

I agree it's been a bit of time since the last release and another one is warranted. The last week was a bad one for me personally, so I didn't have the time to do a release. I'll make sure to get one out this week.

**Comment by timothycrosley** [comment]
isort 5.9.0 has just been released to PyPI: https://github.com/PyCQA/isort/releases/tag/5.9.0
