### ISSUE TITLE
Documentation not working correctly

### ISSUE THREAD

**Issue by Lars147** [PyCQA/isort#1753]
Hi there,

I noticed that some links on the isort documentation pages are broken. For now, I noticed it only for the page https://pycqa.github.io/isort/docs/major_releases/introducing_isort_5.html.

The listed links on this page are redirecting to pages ending with a trailing "/". 

However, the links should end with ".html" in order to work.

**Comment by anirudnits** [comment]
@Lars147 thanks for pointing this out, I've corrected the links in the docs. Hope I got them all!
