### ISSUE TITLE
Broken page in readthedocs

### ISSUE THREAD

**Issue by z00sts** [PyCQA/isort#1755]
Link to profiles is kinda broken: https://pycqa.github.io/isort/docs/configuration/profiles/

**Comment by timothycrosley** [comment]
Hi @z00sts,

Thank you for raising this issue! @anirudnits has fixed it in the PR here https://github.com/PyCQA/isort/pull/1757 (thanks!)

**Comment by z00sts** [comment]
I am sorry, but page is still broken: https://pycqa.github.io/isort/docs/configuration/profiles/

![image](https://user-images.githubusercontent.com/5012880/122732673-b6e81800-d2a6-11eb-9e20-849a29395f97.png)
![image](https://user-images.githubusercontent.com/5012880/122732711-c10a1680-d2a6-11eb-9f4d-581c0e14c868.png)

**Comment by timothycrosley** [comment]
@z00sts, Sorry for the confusion! the correct link is https://pycqa.github.io/isort/docs/configuration/profiles.html, the question is are you still seeing links from elsewhere in the documentation to that incorrect location?

**Comment by z00sts** [comment]
It's ok now!
