### ISSUE TITLE
skip files no longer ignores from stdin

### ISSUE THREAD

**Issue by jeffwillette** [PyCQA/isort#1771]
I had previsouly filed an issue asking for help with ignoring `__init__.py` files https://github.com/PyCQA/isort/issues/1632. Along the way, something changed and this command no longer ignores `__init__.py` files. The way the command is being run is as follows...

```
isort --skip __init__.py --filter-files - < ./__init__.py
```

It might seem a little bit strange to skip a file and then read it from stdin, but this happens because NeoVim + ALE (https://github.com/dense-analysis/ale) runs isort on every save and reads from the current vim buffer which usually has a filepath of something like `/tmp/<random chars>/__init__.py.` To the best of my knowledge, NeoVim and ALE have always read from stdin, so it is very unlikely that the behavior on that end has changed. 

Has there been any change within some of the recent isort versions which might have changed this behavior?

**Comment by timothycrosley** [comment]
Hi @jeffwillette,

I'm sorry for the confusion! However, as written, I cannot see how it could work on any version of isort or any command in general. 

`isort --skip __init__.py --filter-files - < ./__init__.py` doesn't provide any identification of the filename being passed in. isort does provide a way to specify the filename when sorting via a stream that you should work:

`isort --skip __init__.py --filter-files --filename __init__.py - < ./__init__.py`

**Comment by jeffwillette** [comment]
that could potentially work with some work to the plugin. I tried running it on the shell and I got an exception that was raised. Is this exception expected? It seems like it should be handled gracefully instead of raising an exception...

```
Traceback (most recent call last):
  File "/home/jeff/.venv/env/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/home/jeff/.venv/env/lib/python3.8/site-packages/isort/main.py", line 1101, in main
    api.sort_stream(
  File "/home/jeff/.venv/env/lib/python3.8/site-packages/isort/api.py", line 188, in sort_stream
    raise FileSkipSetting(content_source)
isort.exceptions.FileSkipSetting: __init__.py was skipped as it's listed in 'skip' setting or matches a glob in 'skip_glob' setting
```

**Comment by timothycrosley** [comment]
@jeffwillette good call out! I've improved this behavior so the skip will be silent in 5.9.2
