### ISSUE TITLE
isort  configuration compatible with black

### ISSUE THREAD

**Issue by shahzebsiddiqui** [PyCQA/isort#1778]
This is my `.isort.cfg` file i am using to be compatible with black according to https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html even though i am using isort 5.x

```
[setting]
profile = "black"
src_paths = ["buildtest", "tests", "docs"]
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line_length = 88
```

When i run `isort --show-config` it doesn't pick up all of these configuration lines for some reason and I am not sure whats going on. 

```
(buildtest) bash-3.2$ isort --show-config | grep -i include_trailing_comma
    "include_trailing_comma": false,
            "include_trailing_comma": false,

(buildtest) bash-3.2$ isort --show-config | grep -i force_grid_wrap
    "force_grid_wrap": 0,
            "force_grid_wrap": 0,

(buildtest) bash-3.2$ isort --show-config | grep -i include_trailing_comma
    "include_trailing_comma": false,
            "include_trailing_comma": false,

(buildtest) bash-3.2$ isort --show-config | grep -i ensure_newline_before_comments
            "ensure_newline_before_comments": false,
    "ensure_newline_before_comments": false,

(buildtest) bash-3.2$ isort --show-config | grep -i line_length 
    "line_length": 79,
            "line_length": 79,
```

I have noticed that isort and black are not configured properly i run isort before running black and i am getting errors from black because i dont have the right configuration

Here is run isort

```
(buildtest) bash-3.2$ isort buildtest docs/ test -c --profile black
ERROR: /Users/siddiq90/Documents/GitHubDesktop/buildtest/buildtest/config.py Imports are incorrectly sorted and/or formatted.
ERROR: /Users/siddiq90/Documents/GitHubDesktop/buildtest/buildtest/main.py Imports are incorrectly sorted and/or formatted.
ERROR: /Users/siddiq90/Documents/GitHubDesktop/buildtest/buildtest/buildsystem/base.py Imports are incorrectly sorted and/or formatted.
ERROR: /Users/siddiq90/Documents/GitHubDesktop/buildtest/buildtest/cli/build.py Imports are incorrectly sorted and/or formatted.
ERROR: /Users/siddiq90/Documents/GitHubDesktop/buildtest/buildtest/cli/buildspec.py Imports are incorrectly sorted and/or formatted.
Skipped 1 files
Broken 1 paths
```

Now i run isort

```
(buildtest) bash-3.2$ isort buildtest docs/ test --profile black
Fixing /Users/siddiq90/Documents/GitHubDesktop/buildtest/buildtest/config.py
Fixing /Users/siddiq90/Documents/GitHubDesktop/buildtest/buildtest/main.py
Fixing /Users/siddiq90/Documents/GitHubDesktop/buildtest/buildtest/buildsystem/base.py
Fixing /Users/siddiq90/Documents/GitHubDesktop/buildtest/buildtest/cli/build.py
Fixing /Users/siddiq90/Documents/GitHubDesktop/buildtest/buildtest/cli/buildspec.py
Skipped 1 files
Broken 1 paths
```

Now when i run black i am getting that it is formatting the code because it didnt register the isort configuration from my `.isort.cfg` 

```
(buildtest) bash-3.2$ black --diff buildtest docs/ tests
--- tests/buildsystem/test_batch.py	2021-07-09 03:16:43.011252 +0000
+++ tests/buildsystem/test_batch.py	2021-07-09 16:33:28.246890 +0000
@@ -1,7 +1,10 @@
-from buildtest.buildsystem.batch import (CobaltBatchScript, LSFBatchScript,
-                                         SlurmBatchScript)
+from buildtest.buildsystem.batch import (
+    CobaltBatchScript,
+    LSFBatchScript,
+    SlurmBatchScript,
+)
 
 
 def test_batchscript_example1():
     batch_cmds = {
         "account": "biology",
would reformat tests/buildsystem/test_batch.py
--- tests/cli/test_config.py	2021-07-09 03:16:43.049340 +0000
+++ tests/cli/test_config.py	2021-07-09 16:33:28.300554 +0000
@@ -1,11 +1,16 @@
 import os
 
 import pytest
 
-from buildtest.cli.config import (validate_config, view_configuration,
-                                  view_executors, view_summary, view_system)
+from buildtest.cli.config import (
+    validate_config,
+    view_configuration,
+    view_executors,
+    view_summary,
+    view_system,
+)
 from buildtest.config import SiteConfiguration
 from buildtest.defaults import DEFAULT_SETTINGS_SCHEMA, SCHEMA_ROOT
 from buildtest.executors.setup import BuildExecutor
 from buildtest.schemas.defaults import custom_validator
 from buildtest.schemas.utils import load_recipe, load_schema
would reformat tests/cli/test_config.py
--- tests/utils/test_file.py	2021-07-09 03:16:43.022470 +0000
+++ tests/utils/test_file.py	2021-07-09 16:33:28.481211 +0000
@@ -6,13 +6,21 @@
 import uuid
 
 import pytest
 
 from buildtest.exceptions import BuildTestError
-from buildtest.utils.file import (create_dir, is_dir, is_file, load_json,
-                                  read_file, remove_file, resolve_path,
-                                  walk_tree, write_file)
+from buildtest.utils.file import (
+    create_dir,
+    is_dir,
+    is_file,
+    load_json,
+    read_file,
+    remove_file,
+    resolve_path,
+    walk_tree,
+    write_file,
+)
 
 here = os.path.dirname(os.path.abspath(__file__))
 
 
 @pytest.mark.utility
would reformat tests/utils/test_file.py
All done! ✨ 🍰 ✨
3 files would be reformatted, 81 files would be left unchanged.
```

I am trying to add this capability in https://github.com/buildtesters/buildtest/pull/798 see job https://github.com/buildtesters/buildtest/pull/798/checks?check_run_id=3025238162. I am running isort before running black check. It is failing because for some reason `isort` is not picking up the configuration or my `.isort.cfg` is not correct. How can i fix this issue. I have also setup a pre-commit hook so that i can get both checks working.

Here is what the pre-commit looks like when i run `git commit`

```
(buildtest) bash-3.2$ git add tests/
(buildtest) bash-3.2$ git commit
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /Users/siddiq90/Documents/GitHubDesktop/buildtest/tests/buildsystem/test_batch.py
Fixing /Users/siddiq90/Documents/GitHubDesktop/buildtest/tests/utils/test_file.py
Fixing /Users/siddiq90/Documents/GitHubDesktop/buildtest/tests/cli/test_config.py
Skipped 1 files

black....................................................................Passed
```

This is my file and i just run `pre-commit install` and it registers both hooks. 

```
(buildtest) bash-3.2$ cat .pre-commit-config.yaml 
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "buildtest", "tests", "docs"]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.7
```

**Comment by timothycrosley** [comment]
Hi @shahzebsiddiqui,

I'm sorry you are running into an issue here, but I'm happy isort's diagnostic features are helping to identify it! 

From your shared config, I think the issue is as simple as you are using an invalid config section:

```
[setting] <--- here
profile = "black"
src_paths = ["buildtest", "tests", "docs"]
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line_length = 88
```

Instead of `setting` that should be `settings`, so:

```
[settings]
profile = "black"
src_paths = ["buildtest", "tests", "docs"]
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line_length = 88
```
In general isort follows the same pattern as most tools and does not complain if there is no configs set for itself within a config file like is the case here since they are all under a section isort never checks.

For further reference, isort has its own rather comprehensive documentation pages for black compatibility: https://pycqa.github.io/isort/docs/configuration/black_compatibility.html and config files https://pycqa.github.io/isort/docs/configuration/config_files.html

I hope this is helpful! 

~Timothy

**Comment by shahzebsiddiqui** [comment]
@timothycrosley thanks for finding this mistake, it was bit hard to troubleshoot this, it also turns out that in `.isort.cfg` i can't have quotes so `profile = "black"` was not right it was suppose to be `profile = black`

The error i got was

```
(buildtest) bash-3.2$ isort buildtest tests docs/
Traceback (most recent call last):
  File "/Users/siddiq90/.local/share/virtualenvs/buildtest-KLOcDrW0/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/Users/siddiq90/.local/share/virtualenvs/buildtest-KLOcDrW0/lib/python3.7/site-packages/isort/main.py", line 1081, in main
    config = Config(**config_dict)
  File "/Users/siddiq90/.local/share/virtualenvs/buildtest-KLOcDrW0/lib/python3.7/site-packages/isort/settings.py", line 359, in __init__
    raise ProfileDoesNotExist(profile_name)
isort.exceptions.ProfileDoesNotExist: Specified profile of "black" does not exist. Available profiles: black,django,pycharm,google,open_stack,plone,attrs,hug,wemake,appnexus.
```

I was successful in getting isort + black to work in my github workflow i run `isort` before running `black` though i am not sure if i still need to run `black` if i am running isort with black profile. See https://github.com/buildtesters/buildtest/pull/798/checks?check_run_id=3036165071

Just another word of clarification, in my pre-commit hook i run `isort` before running `black` is their a recommendation w.r.t order of how these should run. I would think `isort` needs to run after `black` since running black before running isort can result in failures from black if isort configuration is incompatible.

In my commit, the workflow looks like this. isort runs followed by black. If their is a failure i would run the command manually and rerun `git commit`.

```
(buildtest) bash-3.2$ git commit -m "error in pyflakes CI"
isort....................................................................Passed
black....................................................................Passed
[isort 92abcb44] error in pyflakes CI
```

One last question I was bit confused in the documentation there are two different pre-commit examples, it's bit confusing which ones we should use. The black one makes sense though i see different `rev` number not sure why. Is that the version of black? 

https://pycqa.github.io/isort/docs/configuration/pre-commit.html

```
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
```

https://pycqa.github.io/isort/docs/configuration/black_compatibility.html

```
- repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
```

**Comment by timothycrosley** [comment]
> I was successful in getting isort + black to work in my github workflow i run isort before running black though i am not sure if i still need to run black if i am running isort with black profile. See https://github.com/buildtesters/buildtest/pull/798/checks?check_run_id=3036165071

Glad you were successful! Black and isort both need to get ran, independent of profile. I know that, in say, the go ecosystem goimports runs goformat. But, that is because of how the tools grew together. In isort's case it has existed much longer than black, and they run and do things independently. The profile just ensures the output is compatible. 

> Just another word of clarification, in my pre-commit hook i run isort before running black is their a recommendation w.r.t order of how these should run. I would think isort needs to run after black since running black before running isort can result in failures from black if isort configuration is incompatible.

It really doesn't matter which order, either way you will get errors if they are incompatble. The answer is only they must be made compatible using the profile and the same line lengths. As detailed both in isort and black's documentation. 

> One last question I was bit confused in the documentation there are two different pre-commit examples, it's bit confusing which ones we should use. The black one makes sense though i see different rev number not sure why. Is that the version of black?

That's the version of isort, and really the latest version should be used, pre-commit just forces you to specify the version and the documentation is statically wirtten in this section. 

```
- repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
      - id: isort
        args: ["--filter-files"]
```

is most likely what you want, any of them will work! This version is just taking advantage of the fact isort already includes the correct file identifcation in it's definition so it doesn't need to be restated.

**Comment by shahzebsiddiqui** [comment]
Thanks for the clarification @timothycrosley you answered all my questions. Appreciate your help.
