### ISSUE TITLE
Use lowercase `noqa` instead of uppercase `NOQA` when `multi_line_output=7`

### ISSUE THREAD

**Issue by amano-takahisa** [PyCQA/isort#1782]
In current implementation, `multi_line_output=7` (7-noqa) will produce the code like following.
```Python
from typing import TYPE_CHECKING, Any, Callable, List, Literal, Optional, Tuple, Union  # NOQA
```
Since most of the code out there, the official flake8 documentation, and even within the isort project, people use lowercase `noqa` instead of uppercase `NOQA`.
Is it possible to change the implementation to the following?
Because linters ignore all errors if `noqa` doesn't have error code, I think it is better to indicate the error code following the `noqa`.
```Python
from typing import TYPE_CHECKING, Any, Callable, List, Literal, Optional, Tuple, Union  # noqa: E501
```

**Comment by timothycrosley** [comment]
Hi @amano-takahisa, 

I agree with you, though I'm not a huge advocate of the noqa setting in general. [isort's formatting guarantee](https://pycqa.github.io/isort/docs/major_releases/release_policy.html#formatting-guarantees) however, does mean that any such change would have to wait for the next major release. Alternatively, a new mode could be set up with the lowercase form that then becomes the default in the next release.

Thanks!

~Timothy
