### ISSUE TITLE
Configuring sorting in pyx/pxd files with `import` and `cimport` statements

### ISSUE THREAD

**Issue by charlesbluca** [PyCQA/isort#1787]
I am using isort 5.6.4 to resort pyx/pxd files with a mix of `import` and `cimport` statements. When doing this, I notice that sandwiching `imports` between `cimports` (or vice versa) causes each block of consecutive `import`/`cimports` to be treated as a separate block of imports, and sorted accordingly. For example

```python
isort.code("""
cimport f
import e
cimport d
import c
cimport b
import a
""")
```

Would result in the following:

```python
cimport f

import e

cimport d

import c

cimport b

import a
```

This can become an issue when these "blocks" are only one line each, as it effectively means that isort is unable to resort the imports in any meaningful way, as shown above. With this in mind, is there a way to configure isort in this situation such that:

- Imports are sorted alphabetically regardless of type?

```python
import a
cimport b
import c
cimport d
import e
cimport f
```

- Imports are sectioned by type, then sorted accordingly?

```python
import a
import c
import e

cimport b
cimport d
cimport f
```

**Comment by timothycrosley** [comment]
Hi @charlesbluca, 

I certainly agree the proposal's here would make mixed import usage much nicer! Unfortunately, the current way that cimport support is implemented, makes this very difficult to do. This is unlikely to be supported in the short term, but I'll keep this ticket open, and will consider ideas for how this could be supported in the future.

Thanks!

~Timothy
