### ISSUE TITLE
inconsistent isorting sorting between local and CI execution

### ISSUE THREAD

**Issue by ssbarnea** [PyCQA/isort#1790]
I am running [isort as a pre-commit hook](https://github.com/ansible-community/molecule-containers/blob/main/.pre-commit-config.yaml#L3-L6) for a good number of years and I recently encountered a case where isort makes decision to make changes in an unpredictable.

Basically it flaps between this change and its revert on local and CI:

![ss](https://sbarnea.com/ss/Screen-Shot-2021-07-23-11-48-11.04.png)

- As pre-commit ensures that exact same version is used on both it cannot be that. My only suspicion is that this may be caused by different version of python between local and CI.
- I tried using versions older than 5.9.2 but it seems to do the same.
- After that I suspect that maybe the python major version may be what it causes it to decide different behavior and I made some changes to enforce it to always use python3.9, still the same result.

Any ideas about what causes this and how can I avoid it?

**Comment by timothycrosley** [comment]
Is it possible that you're CI setup is downloading molecule in the same directory as your source code, causing isort to see it as an internal package in CI?

**Comment by ssbarnea** [comment]
I have no reasons to believe this, is github actions that runs tox, almost identical with local runs.

Still there is a "molecule" folder at the root of the project that is *not* a python package, maybe that is confusing isort. I wanted to move towards the better src/ layout, maybe i should do it now, something i did already on most projects.

**Comment by timothycrosley** [comment]
> Still there is a "molecule" folder at the root of the project that is not a python package,

isort doesn't investigate if it's a python package, mostly because it's really hard to know statically, and really technically if it is a folder it is a package, in modern Python:

```
python -c "import hello; print(hello.__path__)
_NamespacePath(['... /hello'])
```

Does that directory only exist in CI? I don't see it in the public source repository linked

**Comment by ssbarnea** [comment]
The repository is the https://github.com/ansible-community/molecule-containers/ but just not I realised that the `./molecule` folder exists only on my local machine and is empty, looking like:
```
$ tree molecule
molecule
└── default
```

As these are only folders git did not report them, but it seems that this was enough to make isort change its behavior. 

Should this be counted as a bug in isort or not? I see no problem if we close it as a support issue but I am afraid that i may have discovered something that is not very unlikely to happen for others. Presence of empty directories should not affect isort behavior, especially as git does not see them.

@timothycrosley a big thanks for taking time to look at this one.

**Comment by timothycrosley** [comment]
@ssbarnea happy to look into issues like this! Very relieved to hear that there was indeed a difference in files. Inconsistencies across environments is one of the things I tried very hard to fix in 5.0.0+.

```
Should this be counted as a bug in isort or not? I see no problem if we close it as a support issue but I am afraid that i may have discovered something that is not very unlikely to happen for others. Presence of empty directories should not affect isort behavior, especially as git does not see them.
```

It's a quirk for sure, but I don't think it's a bug just because you can indeed import that name in Python, so isort is doing the right thing, it's just a very easy to fall into corner case. If nothing else I should probably mention it in the docs. 

One other thing I noticed in the linked project is that you are using black alongside isort, which is awesome! I didn't see the black profile set, but I could have missed it. There is a guide here on how to do that: https://pycqa.github.io/isort/docs/configuration/black_compatibility.html. Having that set would also give you a central place to tell isort how to handle this package. The best thing would probably be to explicitly tell isort what your source directories are, so it can't get confused. Here's an example of both put together, that could be placed in your existing pyproject.toml config file:

```
[tool.isort]
profile = "black"
src_paths = ["molecule_containers"]
```

**Comment by ssbarnea** [comment]
Hehe, if you click blame on file you will see that I removed the profile = black yesterday while investigating this quirk. I will add it back.

Conclusion is that we discovered one extra reason why having a "src" folders instead of keeping packages at repository root is a really good idea. I will do the switch to src right away.  With src folder, is very unlikely to get a random new directory there that would confuse it.

**Comment by ssbarnea** [comment]
I tried switching to src/ layout and what I found was that isort still sorts things differently if `molecule` folder exists. In fact I believe that it will consider any root folder as a local package regardless if they have a `__init__.py` in them or not, causing unpredictable behavior.

For this reason I think we should keep this bug open and look to fix it. Detection logic should ignore any folders that are not modules.

For the moment the workaround is to force mypy to look only into src folder, if you have one:
```toml
# pyproject.toml
[tool.isort]
src_paths = ["src"]
```

**Comment by timothycrosley** [comment]
> For this reason I think we should keep this bug open and look to fix it. Detection logic should ignore any folders that are not modules.

Again, unfortunately, so will Python!  You're solution of setting the src_paths is correct. Setting the `src_path` here, is just like setting the mypy path here: https://github.com/ansible-community/molecule-containers/commit/13063001c09e3a0a577c2d5364b6a8d256c0337d#diff-6f2d4ba9ca9a357d31014946667b7bed1bfdbc6d2530afc77778fa0a36bee457R7. Without an explicit guide, isort can't really know for sure statically what is and isn't a package, and too intense of introspection opens more areas for inconsistency or hard to track down bugs.

**Comment by ssbarnea** [comment]
I don't think there is anything intense about checking the presence of `dirname/__init__.py`, that is what others are doing, including python itself.  In fact what bothers me the most around this issue is that so easy to miss it when folder is empty, as git does not report anything.  Probably time will tell if others encounter the same bug or not. If is very rare we can probably live with it :p

**Comment by timothycrosley** [comment]
> I don't think there is anything intense about checking the presence of dirname/__init__.py, that is what others are doing, including python itself. 

It's just that that isn't true any more, like my pasted example shows, since Python added support for implicit namespace packages, you can just create a large nesting of directories and import them from Python. It certainly used to be true.

**Comment by verbosus** [comment]
In googlefonts/ufo2ft repo we ran into what looks like a variant of the same issue: if I ran `isort` from the root _and the root folder itself was called `ufo2ft`_ we would get one behavior, if the root folder was called something else, we would get another. I wrote about it [in this comment](https://github.com/googlefonts/ufo2ft/pull/527#issuecomment-904625427).

**Comment by fiendish** [comment]
Problem occurs for me because the pyproject.toml was located at a higher directory level than what I'm trying to isort, so it creates a found-local-dir vs installed-package conflict. My solution was moving the pyproject.toml to be next to the package I'm trying to sort imports in instead of up a directory.
