### ISSUE TITLE
Running isort twice results in different code output

### ISSUE THREAD

**Issue by smartsammler** [PyCQA/isort#1799]
Thank you for this helpful software.
I ran into some behaviour that was not intuitive to me, nor stated at the front page :)

Running isort two times on one file results in different results.
This is not optimal if one runs it via pre-commit and in one's CI pipeline with `--check`, as the latter fails.
I checked it with isort 5.5.1 and 5.9.3.

My code which failed first:
`pip install isort`

code (`__init__.py`):
```python
import sys

if sys.version_info[:2] >= (3, 8):
    # TODO: Import directly (no need for conditional) when `python_requires = >= 3.8`
    from importlib.metadata import PackageNotFoundError, version  # pragma: no cover
else:
    from importlib_metadata import PackageNotFoundError, version  # pragma: no cover
```

commands that fail/are not intuitive (`test_run_isort_twice.py`):
```python
with open('__init__.py') as fobj: data = fobj.read()

import isort
settings = isort.settings.Config('.isort.cfg')                                         
assert isort.code(data, settings) == isort.code(isort.code(data, settings), settings)
```
isort config (`.isort.cfg`):
```ini
[isort]
profile=black
src_paths=isort,test
line_length=100
skip=.tox,.venv,build,dist,docs,tests
extra_standard_library=pkg_resources,setuptools,typing
known_test=pytest
known_first_party=ibpt
sections=FUTURE,STDLIB,TEST,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
import_heading_firstparty=internal
import_heading_thirdparty=external
```
But also a more minimal version results in this with an empty .isort.cfg
```ini
[isort]
```
.

After the first run, there are parentheses around the two lines around `PackageNotFoundError` and `version`.
After the second run, there are two lines without the parentheses but with two `from importlib_metadat import`.

**Comment by timothycrosley** [comment]
Hi @smartsammler,

I'm sorry your experiencing this behavior! However, while there may be some cases lurking that should be fixed, where isort is only eventually consistent - and I believe this is alluding with to one such case, it wouldn't actually be for your config file, if the correct parameters where passed in the isort execution:

```
assert isort.code(data, config=settings) == isort.code(isort.code(data, config=settings), config=settings)
```

vs

```
assert isort.code(data, settings) == isort.code(isort.code(data, settings), settings)
```

See your exact provided test case passing here:

https://github.com/PyCQA/isort/commit/c29c6d6c0eaa9ed987157593822e501e89ca02b1

The second argument to `isort.code` is the extension not the config file, use of mypy or another typechecker would catch this at typechecking time:

https://pycqa.github.io/isort/reference/isort/api.html#sort_code_string

**Comment by smartsammler** [comment]
Hi @timothycrosley ,
Oh, I'm very sorry to have bothered you with this.
Thank you so much for pointing this out to me and once again thanks for this project.
