### ISSUE TITLE
broken url

### ISSUE THREAD

**Issue by shahzebsiddiqui** [PyCQA/isort#1803]
I happened to find out in my urlcheck workflow (https://github.com/buildtesters/buildtest/pull/856/checks?check_run_id=3315985294) the following link: https://pycqa.github.io/isort/docs/configuration/black_compatibility.html was broken.

This is the second bullet point in the main page please fix the link 
![Screen Shot 2021-08-12 at 4 47 01 PM](https://user-images.githubusercontent.com/12942230/129267471-daf40289-2458-4f9d-9f53-df3105bb4dc6.png)

**Comment by timothycrosley** [comment]
Thanks for reporting this! There is something weird going on here with a patch version of mkdocs changing how the docs are outputted (and therefore what links are valid). I've pushed using an older version of mkdocs for now to fix the links.

**Comment by shahzebsiddiqui** [comment]
Thanks @timothycrosley it works now. Yea i would recommend setting up the URL check workflow for the user docs it helps trackdown any broken links specially when you have external links that get moved due to any various factors. 

Here are two of my workflows one works on `devel` and other works on cron basis
- https://github.com/buildtesters/buildtest/blob/devel/.github/workflows/urlchecker.yml
- https://github.com/buildtesters/buildtest/blob/devel/.github/workflows/urlcheck_cron.yml
