### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by anirudnits** [PyCQA/isort#1811]
`isort` sorts this import section:
```python
from collections import (
    defaultdict,
    Counter,
    deque, # this is a comment
    OrderedDict,
)
```
to
```python
from collections import deque  # this is a comment
from collections import Counter, OrderedDict, defaultdict
```
I'm using isort:5.9.3 with default configurations. I'm not exactly sure where the comment should be placed in the sorted section, either way splitting the imports seem weird to me.

**Comment by timothycrosley** [comment]
isort is doing this because depending on the grouping method, the attachment of the comment can be lost. In this example if say they all fit on one line: 

```
from collections import Counter, OrderedDict, deque, defaultdict  # this is a comment
```
would be the alternative sort, but then the association of the comment with deque is lost.

**Comment by DetachHead** [comment]
in cases like that i would expect it to keep the imports on separate lines regardless of length, in order to keep the comments in the right spot. see #1847

**Comment by timothycrosley** [comment]
@DetachHead but moving it to it's own line is the only way to keep it in the correct spot independent of import style used.
