### ISSUE TITLE
Improve 'path not found' error message

### ISSUE THREAD

**Issue by Ionaru** [PyCQA/isort#1813]
When isort cannot find the path it is supposed to run for, it prints the message `broken n paths`, where `n` is the number of paths/directories that were not found.

This message is unclear, and could be improved with this information:

- Something to let the user know this error came from isort.
- Some feedback on the paths that are "broken".

For example
```bash
$ isort some_dir
isort: "some_dir" does not exist.
```

```bash
$ isort some_dir some_other_dir/some_file.py
isort: Path "some_dir" does not exist.
isort: Path "some_other_dir/some_file.py" does not exist.
```

**Comment by anirudnits** [comment]
Hey @Ionaru, you can get a more verbose error message with specific broken paths listed, by using the `--verbose` flag. The verbose error message will look something like this:
`UserWarning: non-existent-path was broken path, make sure it exists correctly
` 

Hope this helps.

~ Aniruddha

**Comment by Ionaru** [comment]
In our experience the `--verbose` flag makes it very difficult to see problems when running it together with the `--check` flag, so we usually don't have the `--verbose` flag enabled in our CI system.

As I understand it, broken paths are not treated as errors, is that correct?

**Comment by anirudnits** [comment]
> As I understand it, broken paths are not treated as errors, is that correct? 

If **all** paths are broken then isort will exit with a non-zero exit code, so the CI job would fail. https://github.com/PyCQA/isort/blob/995e016b9d888fea02bedeb5be8ea7f01b694b58/isort/main.py#L1247

So something like `isort non-existent-path another-non-existent-path --check` will exit with return code 1, thus failing the job.

**Comment by jamiesandenr** [comment]
> > As I understand it, broken paths are not treated as errors, is that correct?
> 
> If **all** paths are broken then isort will exit with a non-zero exit code, so the CI job would fail.
> 
> https://github.com/PyCQA/isort/blob/995e016b9d888fea02bedeb5be8ea7f01b694b58/isort/main.py#L1247
> 
> So something like `isort non-existent-path another-non-existent-path --check` will exit with return code 1, thus failing the job.

This is quite strange behaviour.  If I do `isort exists doesnt_exist --check` then the error code is 0 so my CI pipeline passes.  Is this intentional?
