### ISSUE TITLE
How to sort __init__.py / `--dont-skip` not honored.

### ISSUE THREAD

**Issue by dandavison** [PyCQA/isort#183]
`__init__.py` files are [skipped by default](https://github.com/timothycrosley/isort/blob/develop/isort/settings.py#L45). Out of interest, why is this? But more importantly, how can we override it from the command line? It seems that the `--dont-skip` option is [present](https://github.com/timothycrosley/isort/blob/develop/isort/main.py#L51) but I believe not honored. (I don't see any other [occurrences](https://github.com/timothycrosley/isort/search?utf8=%E2%9C%93&q=not_skip) of `not_skip` in the code).

**Comment by edmorley** [comment]
> Would still be interested to know why __init__.py is excluded by default; it seems a bit error-prone for new users who might think their __init__.pys are sorted.

`__init__.py` being skipped by default came as a surprise to me just now - I came here to report a bug of isort not sorting that file, only to see it's intentionally skipped. Is there a reason for this? :-)
