### ISSUE TITLE
Problem in integrating isort with pre-commit

### ISSUE THREAD

**Issue by 42dmc** [PyCQA/isort#1832]
Isort returns failure every time Pre-Commit runs.

![Screenshot from 2021-10-26 04-29-02](https://user-images.githubusercontent.com/92567119/138829722-2771028c-5739-4af9-a91e-a60fe632c154.png)
![Screenshot from 2021-10-26 04-29-15](https://user-images.githubusercontent.com/92567119/138829727-82edde61-86b0-4b9a-9d4b-a8f23cdb8cc2.png)
![Screenshot from 2021-10-26 04-29-19](https://user-images.githubusercontent.com/92567119/138829733-eb73b11a-37f2-475b-8d4d-4520b32a4f63.png)
![Screenshot from 2021-10-26 04-29-22](https://user-images.githubusercontent.com/92567119/138829737-bef8d7f7-61f8-4fca-9330-e594972f0123.png)
![Screenshot from 2021-10-26 04-29-25](https://user-images.githubusercontent.com/92567119/138829740-ffd220b9-a3e1-46fd-b443-df31777896a1.png)
![Screenshot from 2021-10-26 04-29-40](https://user-images.githubusercontent.com/92567119/138829744-7b90db77-1b83-4c02-943a-eba9eb2749de.png)
![Screenshot from 2021-10-26 04-30-02](https://user-images.githubusercontent.com/92567119/138829748-ce2f9934-2a43-48cc-b764-9674ad834330.png)
![Screenshot from 2021-10-26 04-30-16](https://user-images.githubusercontent.com/92567119/138829751-6d089ae9-e32b-4097-8189-6367c3de0713.png)

**Comment by 42dmc** [comment]
Hi! I got tired of trying to use pre-commit. I'm going back to the Makefile. Sorry for the inconvenience.

**Comment by Corfucinas** [comment]
This error is happening to me as well on #1872

**Comment by Corfucinas** [comment]
This error is happening to me as well on #1872

**Comment by Corfucinas** [comment]
This error is happening to me as well on #1890
