### ISSUE TITLE
Should `force_single_line` respect `force_grid_wrap`?

### ISSUE THREAD

**Issue by thanhph111** [PyCQA/isort#1836]
I've tried searching through the documentation but there doesn't seem to be a configuration that solves my case.

With this config...
```toml
force_single_line = true
force_grid_wrap = 3
multi_line_output = 3
```
...I expect _isort_ to...

<table>
<tr>
    <th>turn this...</th>
    <th>to this...</th>
</tr>
<tr>
<td>

```python
from abc import ABC
from abc import abstractmethod
from typing import Generic
from typing import SupportsIndex
from typing import TypeVar
import pulp
```

</td>
<td>

```python
from abc import ABC
from abc import abstractmethod
from typing import (
    Generic,
    SupportsIndex,
    TypeVar
)

import pulp
```

</td>
</tr>
</table>

..but I've actually got this...
```python
from abc import ABC
from abc import abstractmethod
from typing import Generic
from typing import SupportsIndex
from typing import TypeVar

import pulp
```

I mean the formatted lines I expect are still single lines, right?
Is there any settings I missed can help me achieve this result?

If not, can we have a new one? Or we can make the `force_grid_wrap` prioritize the `force_single_line`. It will prevent the conflicts with other `multi_line_output` values.

I'm using _Black_ with this form for a long time and I find it very well suited for the target of **minimizing diffs**.

**Comment by timothycrosley** [comment]
force_single_line, means to force imports to be in the single line format, such as `from typing import Generic`, by definition, grid wrapping requires multiple lines. I think all that's needed to do what you want is to get rid of the option, you do not want, `force_single_line`. `force_grid_wrap` + `multi_line_output = 3` already do exactly what you want.

**Comment by thanhph111** [comment]
Thanks for your info, I did try this configuration and many others but it didn't work.

![image](https://user-images.githubusercontent.com/60842560/139637513-6e099db0-8b22-4c92-8f1f-f6a26613d0f1.png)

Am I missing something?

**Comment by timothycrosley** [comment]
@thanhph111 I can't find any logic in what you expect, maybe you can provide some more details. Why do you expect the imports from typing to be grouped in a grid, but not the imports from abc? What is the logic behind this, that isort could possibly enforce?

**Comment by timothycrosley** [comment]
I think I understand now, running some experiments. What you want is a way to say force a grid wrap after 3 imports, otherwise keep every import on its own line?

**Comment by thanhph111** [comment]
Yeah, that's right. Here I provide some details about my decision. 

Basically, what I want is to **minimize diff**, so all combines is prohibited. But why don't I just use this?

```python
from abc import (
    ABC,
    abstractmethod
)
from typing import (
    Generic,
    SupportsIndex,
    TypeVar
)

import pulp
```
Because the module has 2 imports usually changes to 1, the number of modified lines will be 4 at that time, it's a lot for me. So I think 3 imports is a balanced number.
