### ISSUE TITLE
multiple imports from same module with an alias split into two when sorted

### ISSUE THREAD

**Issue by DetachHead** [PyCQA/isort#1841]
```py
from typing import TypeVar as Z, Generic
```
this gets turned into
```py
from typing import Generic
from typing import TypeVar as Z
```

**Comment by anirudnits** [comment]
Hey @DetachHead, you can get the imports in the same line by using the `--combine-as or --ca` flag, https://github.com/PyCQA/isort/blob/main/docs/configuration/options.md#combine-as-imports. Similar issue: https://github.com/PyCQA/isort/issues/1305.

Hope this helps.
~ Aniruddha

**Comment by KotlinIsland** [comment]
> Hey @DetachHead, you can get the imports in the same line by using the `--combine-as or --ca` flag, https://github.com/PyCQA/isort/blob/main/docs/configuration/options.md#combine-as-imports. Similar issue: #1305.
> 
> Hope this helps. ~ Aniruddha

Whats the motivation behind this default? Seems like a strange choice.

**Comment by KotlinIsland** [comment]
https://github.com/PyCQA/isort/issues/1305#issuecomment-926369825
nvm

**Comment by wieczorek1990** [comment]
For config use: `combine_as_imports = true`.
