### ISSUE TITLE
Whether the isort can clean the package which didn't be used in the code file

### ISSUE THREAD

**Issue by Vincent0706** [PyCQA/isort#1842]
Whether the isort can clean the package which didn't be used in the code file?
The Pycharm can clean the package which didn't be used in the code file. I don't know whether the isort has the same funtion and whether it can be realized.

**Comment by anirudnits** [comment]
Hey @Vincent0706 can you please elaborate? I'm not familiar with this feature from PyCharm and so can't understand what is meant by "cleaning" the package. Does it imply whether isort can remove unused imports from files?

**Comment by Vincent0706** [comment]
Before format:
![image](https://user-images.githubusercontent.com/82581024/140499471-bd553c5b-0069-4103-bb48-1f70abd3e88d.png)

After format:
![image](https://user-images.githubusercontent.com/82581024/140499543-04a6b83c-6012-42ee-b3ee-2d091283a968.png)

You can found that Pycharm delete the import of the package which don't be used in my code.

**Comment by anirudnits** [comment]
No, isort presently doesn't support deleting unused imports. You can find a more detailed discussion on this here: https://github.com/PyCQA/isort/issues/1105.

Hope this helps.

**Comment by Vincent0706** [comment]
ok, thanks a lot
