### ISSUE TITLE
Wrong config file gets precedence silently

### ISSUE THREAD

**Issue by sblask** [PyCQA/isort#1848]
I just tried out the python language server with its isort plugin (https://github.com/paradoxxxzero/pyls-isort) and got very confused when my isort config (`~/.isort.cfg`) wasn't used. After some digging I found that it's apparently the intended behaviour because I have a .editorconfig file in my project directory. I didn't know that that was supported by isort and I don't have any isort related configuration in there.

It's probably too late to change that, but I think the search order should be changed, first look for the most specific config file (`.isort.cfg`) in the directory hierarchy then do the same with the next most specific file (`pyproject.toml`) and so forth. Only config files that actually contain isort configuration should be accepted.

If the search order isn't changed, then at least some information about which configuration file the config comes from should be printed on the command line.

**Comment by anirudnits** [comment]
Hey @sblask thanks for raising this. I haven't yet faced this issue personally but I'll try to recreate the scenario you referenced in the issue. Just from a quick glance, the issue may arise from here: https://github.com/PyCQA/isort/blob/63c7fa4913765a38ec6d65c556bc92c24549e891/isort/settings.py#L96-L101 By replacing the normal `dict` with an `OrderedDict` may solve the issue. I'll look into this when I get some time.

~ Aniruddha

**Comment by sblask** [comment]
I don't think that the problem, it's rather the logic here: https://github.com/PyCQA/isort/blob/63c7fa4913765a38ec6d65c556bc92c24549e891/isort/settings.py#L761
Imagine a directory hierarchy like this:

```
foo
    - bar
        - current
```
With `current` being the current working directory. As it is now the closest supported config file is used, so if there is an `.editorconfig` file in `current` it takes precedence over an `.isort.cfg` in `foo` and I think the most isort-specific config file should take precedence. The only time an `.editorconfig` file should take precedence is when it is closer to `current` than another `.editorconfig`

**Comment by timothycrosley** [comment]
@sblask if that's the case, I think isort is doing the right thing. It's expensive to do filesystem look ups, and it should stop the moment its found the closest config. It provides many options to manually specify the config if desired.

**Comment by sblask** [comment]
@timothycrosley I disagree, but that's ok.

I do have a problem though with there not being any information printed which config file is used. I would never have suspected that my `.editorconfig` (that doesn't contain any isort configuration) takes precedence over my global isort configuration.

Btw, manually specifying the config is not really a thing when using the Python LSP I think.
