### ISSUE TITLE
apply different settings in different subdirectories

### ISSUE THREAD

**Issue by murcake** [PyCQA/isort#1849]
Hi, I have a project-wide isort configuration in `pyproject.toml`. However, in a certain subdirectory I'd like to have different settings. I've created a `.isort.cfg` file in that directory with the desired settings. 

I expect that running `isort .` in the root directory would result in formatting files in that subdirectory according to the rules in the `.isort.cfg`.

I get those files formatted according to the rules in `pyproject.toml`. 

What can I do to achieve the desired?

**Comment by anirudnits** [comment]
This is a recent enhancement to `isort` to support multiple config files across sub-directories. You can find some the flags here: https://github.com/PyCQA/isort/blob/c5e8fa75dda5f764d20f66a215d71c21cfa198e1/isort/main.py#L273 and https://github.com/PyCQA/isort/blob/c5e8fa75dda5f764d20f66a215d71c21cfa198e1/isort/main.py#L265. As an example, you could do something like this
`isort directory --resolve-all-configs --config-root directory` and that should do the trick.

I'll add separate documentation about this in the config files section.

Hope this helps and let me know if there are any more concerns.

~Aniruddha

**Comment by anirudnits** [comment]
#1850

**Comment by murcake** [comment]
Thanks a lot for that feature! It seems to work pretty good in general, but it doesn't seem to account for `supported_extensions`. Here's a minimal subconfig:
```[settings]
line_length=100
known_first_party=evm
supported_extensions=["cairo"]
```

Files like *.cairo don't get reformatted.

**Comment by anirudnits** [comment]
Thanks @murcake for pointing this out! I'll have a look and will work to remediate this in the coming releases. Acting on your question, I added documentation regarding this, you can check it out here: https://github.com/PyCQA/isort/pull/1850/files, if you think that the added documentation lacks in anyway do let me know.

**Comment by murcake** [comment]
The documentation is good)
