### ISSUE TITLE
Pycodestyle version issue;

### ISSUE THREAD

**Issue by sinanislekdemir** [PyCQA/isort#1867]
Hi!
`flake8` 4.0.1 requires `pycodestyle<2.9.0 and >= 2.8.0` but isort fixes pycodestyle to `">=2.7.0,<2.8.0"` creating a conflict. So I can't upgrade flake8 with isort latest version.

**Comment by timothycrosley** [comment]
@sinanislekdemir I'm very curious to what you mean, isort doesn't specify version of pycodestyle at all. Do you by any chance mean a different project and or plugin?
