### ISSUE TITLE
Support non-alphabetic ordering of imports on one line (most used first, grouped by datatype)

### ISSUE THREAD

**Issue by fmalina** [PyCQA/isort#1870]
I have a feature request.

I would like isort to support an alternative mode of operation where it would sort my imports from a single module more naturally.

e.g. when I make an import 

`from module import MuchUsedModel, LessUsedClass, some_util, another_util` ✅

I definitely want this ordering to be kept or improved upon, classes first, followed by functions, not alphabetically, but most important or most used ones first. Currently isort within lines drops the ordering semantics and replaces it with unnatural alphabetical one making my code worse.

`from module import another_util, LessUsedClass, MuchUsedModel, some_util` 😭

**Comment by timothycrosley** [comment]
Hi @fmalina, 

isort does by default have `order_by_type` enabled, if you are using a profile or similar that disables it, you may simply just need to turn it back on. See: https://pycqa.github.io/isort/docs/configuration/options.html#order-by-type

This covers:

```
classes first, followed by functions, 
```

For your second request, I'm sorry to say it's simply out of scope, and personally I don't think practical for isort to do, or for a user to experience. It seems in early development your imports would be jumping all over as you change your code! With very little obvious rhyme or reason as the more usages, would be at the single level. Most importantly though, isort has a streaming architecture. It sorts the imports before it sees any usages. The usages are after the imports, so it doesn't fit with the overall approach isort is taking.

**Comment by fmalina** [comment]
This a shame marking won't fix. Latin alphabet has a completely arbitrary historical ordering inherited from greek and phoenician (A -ox head, O -eye, N -snake, Z -sword). It's all nonsense lost to history :) Usage frequency on the other hand can be a decent importance indicator of an import deserving early introduction to the reader of my code.

**Comment by timothycrosley** [comment]
It's less to do with having deep meaning, but in having consistency! That matters much much more, for finding imports you are looking for, reducing diffs, and avoiding random order, before usage differences are stark.

**Comment by fmalina** [comment]
The order of imports on a line matters and it is more natural to have more prominent classes and code mentioned first. Alphabet is arbitrary. Users would not want their Google results ordered alphabetically, they are ranked by importance. Analysis getting the frequency of all imported modules in a project can be done beforehand as to not interfere with streaming architecture. Counting how many times a module is used can be as easy as `'aa aa bb\n cc'.count('aa')`.

I wonder what are the relevant parts and code in isort to look at if this was to be done on a fork
