### ISSUE TITLE
Have an option to configure separate `import x` from `from x import y`?

### ISSUE THREAD

**Issue by mjr** [PyCQA/isort#1902]
I would like to have the result below, I looked in the documentation, but I did not find if there is a way to configure it this way, with a space between the imports.

```python
import base64
import math

from datetime import datetime
from decimal import Decimal
```

**Comment by anirudnits** [comment]
Hello @mjr, thanks for reaching out! Have you tried the [lines between types](https://github.com/PyCQA/isort/blob/main/docs/configuration/options.md#lines-between-types) option? This should do the trick for the code snippet you referenced here.

**Comment by mjr** [comment]
Thanks @anirudnits, this worked exactly as i expected.
