### ISSUE TITLE
skip and extend_skip being ignore

### ISSUE THREAD

**Issue by LondonAppDev** [PyCQA/isort#1909]
I'm using isort 5.10.1 and I'm trying to exclude additional virtual environment directories using the project config.

In my project, I have a `myproject.toml` file which contains the following for `isort`:

```
[tool.isort]
profile = "black"
src_paths = ["src1", "src2"]
extend_skip = [".env", "env"]
```

If I run `isort .` from the root of my project, it will sort dependencies from all modules inside my virtual environment which sits in a directory called `env` in my project root.

If I call the virtual environment `venv` (which is one of the default `skip` values mentioned in the docs [here](https://pycqa.github.io/isort/docs/configuration/options.html#skip)), then this does appear to be excluded.

It looks like items added to `extend_skip` are not being skipped.

**Comment by mhsmith** [comment]
The [configuration filename](https://pycqa.github.io/isort/docs/configuration/config_files.html) is pyproject.toml, not myproject.toml.

**Comment by LondonAppDev** [comment]
Ah! Thanks @mhsmith. Silly error on my part 😅
