### ISSUE TITLE
Infinite loop on unclosed parenthesis

### ISSUE THREAD

**Issue by andersk** [PyCQA/isort#1917]
If I run isort (5.10.1 or `main` at c6a41965247a858a0afd848fbebfca18b8983917) on this invalid file with an unclosed parenthesis, it goes into a 100% CPU infinite loop:

```python3
from os import (
```

**Comment by anirudnits** [comment]
I'm looking into this. Just as a workaround using `--atomic` flag for such files will raise an error and prevent isort to go into an infinite loop.

**Comment by anirudnits** [comment]
this while condition https://github.com/PyCQA/isort/blob/c6a41965247a858a0afd848fbebfca18b8983917/isort/core.py#L304 seems to be going into infinite loop. There should be way to identify if we are at the end of a stream and raise an error if so.
