### ISSUE TITLE
Feature: make it possible to save the errors into a report file

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [PyCQA/isort#1936]
When running the `isort` command, it prints the error messages into the stdout/stderr. If there is a need to save them into a file, one could just redirect with `>` or `tee` into a file. However, when running `isort` inside a larger workflow where terminal may be filled with other commands output, redirecting may be tricky or not feasible at all. 

I wonder if it would be possible to add a new option to save the errors into a report file? This is how flake8 does it with the [--output-file](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-output-file) option, for example. 

```
$ cat program.py                                       
print( 'foo')
$ flake8 program.py --output-file=report.txt
$ cat report.txt 
program.py:1:7: E201 whitespace after '('
```

Being able to parse such a report file would be very helpful to be able to communicate the issues to the user in a custom way. 

How difficult is it going to be? I am happy to look into the implementation if the maintainers agree this feature would be helpful to add :)

**Comment by doublethefish** [comment]
Why not use `tee`?

```sh
isort [...] | tee isort.log 2>&1
```

**Comment by alexey-tereshenkov-oxb** [comment]
> Why not use `tee`?
> 
> ```shell
> isort [...] | tee isort.log 2>&1
> ```

That's a valid suggestion :) my use case is that isort is run through another piece of software (Pantsbuild) so that I cannot make `isort` run as part of an arbitrary Shell command.

**Comment by alexey-tereshenkov-oxb** [comment]
> Wrap it in a script?

Thanks for brainstorming :) Unfortunately, the only way to interact with Pants is through the configuration of individual tools via arguments, hence the idea for `isort` to report an output with changes it would make.

**Comment by doublethefish** [comment]
If you're using `pants.backend.python.lint.isort` and you can't get something you need there, then the problem is in panstbuild's subsystem.

> Unfortunately, the only way to interact with Pants is through the configuration of individual tools via arguments

That is not correct, for example, you can add custom linters, and specialise existing tools. Pantsbuild would be a *very* poor devops tool if that was the only way.

Just because [flake8 does it](https://en.wikipedia.org/wiki/Argumentum_ad_populum), doesn't mean that [isort should](https://en.wikipedia.org/wiki/Unix_philosophy#Eric_Raymond's_17_Unix_Rules).

**Comment by alexey-tereshenkov-oxb** [comment]
Awesome, thank you for sharing your thoughts on this. :)

**Comment by doublethefish** [comment]
Wrap it in a script?
