### ISSUE TITLE
isort limits python_require <4.0 (again)

### ISSUE THREAD

**Issue by sisp** [PyCQA/isort#1945]
In #1877 the issue of having a cap on the Python version was raised. #1878 fixed this problem and was merged. :tada:

@timothycrosley Any specific reason why you re-introduced the cap in 9e4b5ee05264e6e566b18bea88b3073abd4b1014 again? It breaks any downstream project that uses Poetry with an uncapped Python version. :disappointed:

**Comment by staticdev** [comment]
@sisp @yajo fixed on 5.11.0.

**Comment by sisp** [comment]
Thanks, @staticdev! :pray:
