### ISSUE TITLE
No CLI executable on Ubuntu 20.04

### ISSUE THREAD

**Issue by mangelozzi** [PyCQA/isort#1947]
I seem to be the only person not able to get the CLI interface to work. The documentation says the `isort` cmd will be available after installing it. I followed the install instruction. I have tried restarting bash, exiting, reactivating the venv, but it does not work, e.g.:

```
michael@michael:~/project/src$ pip3 install isort
Requirement already satisfied: isort in /usr/lib/python3/dist-packages (4.3.4)
michael@michael:~/project/src$ isort --help

Command 'isort' not found, but can be installed with:

sudo apt install isort
```

I checked the venv `bin/` dir and there is no `isort` executable there. The documentation only mentions one needs to pip install it, I am guessing the `apt` recommendation is something else.

**Comment by sztamas** [comment]
Hi @mangelozzi ,

Could you please provide some further info about your environment?

```
$ echo $VIRTUAL_ENV
$ which pip3
$ which python
$ echo $PATH
$ pip3 show -f isort
```
Thanks!

**Comment by mangelozzi** [comment]
> Hi @mangelozzi ,
> 
> Could you please provide some further info about your environment?
> 
> ```
> $ echo $VIRTUAL_ENV
> $ which pip3
> $ which python
> $ echo $PATH
> $ pip3 show -f isort
> ```
> 
> Thanks!

Thank you for following up with this, heres the info:
```
(project) michael@michael:~/project/src$ echo $VIRTUAL_ENV
/home/michael/.venv/project
(project) michael@michael:~/project/src$ which pip3
/home/michael/.venv/project/bin/pip3
(project) michael@michael:~/project/src$ which python
/home/michael/.venv/project/bin/python
(project) michael@michael:~/project/src$ echo $PATH
/home/michael/.venv/project/bin:/home/michael/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/michael/.fzf/bin
(project) michael@michael:~/project/src$ pip3 show -f isort
Name: isort
Version: 4.3.4
Summary: A Python utility / library to sort Python imports.
Home-page: https://github.com/timothycrosley/isort
Author: Timothy Crosley
Author-email: timothy.crosley@gmail.com
License: MIT
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: 
Files:
Cannot locate RECORD or installed-files.txt
(project) michael@michael:~/project/src$ python --version
Python 3.9.13
```

**Comment by sztamas** [comment]
Thanks for the info!
That looks like an older version of isort.
What happens if you

``pip install --upgrade isort``

?

**Comment by sztamas** [comment]
I'm glad it is solved!

All the best,
Tamas
