### ISSUE TITLE
Failed to use profile `black` in .isort.cfg

### ISSUE THREAD

**Issue by Hongbo-Miao** [PyCQA/isort#1977]
There is an example at https://pycqa.github.io/isort/docs/configuration/config_files.html

> .isort.cfg [preferred format]
> 
> ```
> [settings]
> profile=hug
> src_paths=isort,test
> ```

Based on the document, I tried `.isort.cfg`:

```
[settings]
profile=black
```

However, when I run `isort .`, it gives me error

> Traceback (most recent call last):
>   File "/opt/homebrew/Caskroom/miniconda/base/bin/isort", line 8, in <module>
>     sys.exit(main())
>   File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/isort/main.py", line 1108, in main
>     config = Config(**config_dict)
>   File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/isort/settings.py", line 365, in __init__
>     raise ProfileDoesNotExist(profile_name)
> isort.exceptions.ProfileDoesNotExist: Specified profile of "black" does not exist. Available profiles: black,django,pycharm,google,open_stack,plone,attrs,hug,wemake,appnexus.

If you see last sentence, `black` is one of valid profiles:

> Available profiles: black,django,pycharm,google,open_stack,plone,attrs,hug,wemake,appnexus.

**Comment by sztamas** [comment]
Hi there,

I'm just guessing based on that error message, but is it possible that you have quotes around black in the config file. ie. `profile="black"` instead of `profile=black`?

`.isort.cfg` should have
```
[settings]
profile=black
```

instead of
```
[settings]
profile = "black"
```
This quoted configuration should be used only in a `pyproject.toml`.

**Comment by Hongbo-Miao** [comment]
Thanks @sztamas ! However, I didn't use `"`.

**Comment by Hongbo-Miao** [comment]
Hi @sztamas I think you are right! Thank you sooo much! 😃
