### ISSUE TITLE
VS Code: User defined absolute imports violate PEP8 in Django project

### ISSUE THREAD

**Issue by abdnafees** [PyCQA/isort#1993]
The default behavior of `python.sortImports` is to organize stdlib, 3rd party, and user modules.

However, it moves my user modules above the 3rd part modules in alphabetical order which is not according to PEP8. And, it follows PEP8 when I use relative imports which is making things more difficult.

VS Code settings for isort extension
```
{
    "isort.args": [
        "--profile",
        "django",
        "--known-local-folder",
        "api"
    ],
}
```

Here, is the desired output.

    from django.urls import path
    from rest_framework.authtoken import views
    from rest_framework.urlpatterns import format_suffix_patterns

    from customauth.views import ListUsers, RegisterUser

`customauth` is a user defined Django app, rest of them are 3rd part as you can see.

Actual output from after autoformatting.

    from customauth.views import ListUsers, RegisterUser
    from django.urls import path
    from rest_framework.authtoken import views
    from rest_framework.urlpatterns import format_suffix_patterns

**Comment by kaste** [comment]
Do you really see a bug here?  Isn't that just a question about configuration?  Just asking.

For example, you could use

```
[tool.isort]
profile="django"
known_first_party=["customauth"]
known_local_folder=["api"]
```

that would work for me

**Comment by abdnafees** [comment]
Yeah, I fixed it as you mentioned. 

For future readers. If a local folder is showing up as a 3rd party library then use the following args in your settings.json file.

```
{
    "isort.args": [
        "--profile",
        "django",
        "--known-local-folder",
        "my_folder1",
        "--known-local-folder",
        "my_folder2",
        "--known-local-folder",
        "my_folder3"
    ],
}
```
