### ISSUE TITLE
Support for python 3.11

### ISSUE THREAD

**Issue by XJTLUmedia** [PyCQA/isort#1996]
I'm using vscode version 1.70.0
isort version v2022.3.12771042

when I select python 3.11.0 as interpreter. 
error like this happened `The isort server crashed 5 times in the last 3 minutes. The server will not be restarted.`
It works fine on python 3.10 version
Please take a look at this issue.

**Comment by staticdev** [comment]
Strange, I have many projects I migrated recently to py3.11 and they are working fine with isort. Eg: https://github.com/staticdev/human-readable/
