### ISSUE TITLE
packaging question

### ISSUE THREAD

**Issue by gene-git** [PyCQA/isort#2038]
Building a wheel via : python -m build -w
2 files seem to be in wrong directory:
unzip -l dist/*.whl

Archive:  dist/isort-5.11.2-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
    35069  1980-01-01 00:00   CHANGELOG.md
     1089  1980-01-01 00:00   LICENSE
      871  1980-01-01 00:00   isort/__init__.py
...

When this wheel is installed the 2 errant files land in /usr/lib/python3.10/site-packages
where they don't belong.

**Comment by staticdev** [comment]
Actually these files are added on purpose, you can see on include of pyproject.toml. Also we are using poetry to package, not build module.

**Comment by gene-git** [comment]
poetry build --format wheel produces same problem. Yes I was aware that they were added on purpose - but its still bad in my view, intentional or not.

When these get installed by distro package, unless action is taken to delete, they will land in 

/usr/lib/python3.10/site-packages

where they obviously don't belong.

They should be in their own isort sub-directory. The site-packages directory is meant for all packages not  files like these belonging to isort.

Might I suggest you simply move them down 1 level to:

/usr/lib/python3.10/site-packages/isort/xxx

In meantime, distro packages should delete or move them somewhere more appropriate.

thanks

**Comment by staticdev** [comment]
@gene-git a-ha, I see now. Not sure how to change this behavior though. There is probably an issue reported on poetry then. Do you know?

**Comment by gene-git** [comment]
Sadly the more I use poetry the less I like it - it seems very focused on individual and not on distros.

# ignore me for a bit ... :)
1) The idea of pulling dependent packages from any remote repo is just wrong on so many levels from a security standpoint even for virtual env. This nutty idea I guess possibly came from java world - see how well that worked lol (log4jam).

2) poetry install does not even support --root-dir like pip. 

There have been issues raised with poetry but nothing went anywhere on install destination - which is what is needed for any distro packages. I use pip to install as poetry is not usable.

# im back  .. 

I have not tried this but does just adding isort in the include work?

 include = [
...
    { path = "isort/CHANGELOG.md" },
    { path = "isort/LICENSE" },
]

**Comment by gene-git** [comment]
doesnt work - those are in the sdist but not the wheel.

**Comment by gene-git** [comment]
and obviously  that was silly suggestion on my part.
need more coffee- include references source file relative to pyproject.toml file and does not allow you to specify a destination ... 

I dont see offhand how to make this work for wheel - only for sdist.

**Comment by gene-git** [comment]
Seems to be not possible in poetry  - this bug is unresolved by look of it.

https://github.com/python-poetry/poetry/issues/4494

**Comment by gene-git** [comment]
So whatever the solution is it cannot use poetry include section.
I like poetry even less now lol.

Does this help at all?
https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file

**Comment by gene-git** [comment]
There is a simple solution after all:
This works:
   
   mkdir isort/Docs
  mv LICENSE CHANGELOG.md isort/Docs

No change to pyporject.toml - since project includes "isort" this will also include isort/Docs

**Comment by staticdev** [comment]
@gene-git interesting, I can try. I did not find a reference to that. Do you have a link to share?

**Comment by gene-git** [comment]
your pyproject.toml has
packages = [
    { include = "isort" },
]
so isort and everything under isort  will be in package as per poetry doc.

This is documented : https://python-poetry.org/docs/pyproject/ in Packages section.

**Comment by gene-git** [comment]
Thanks for working on this -but it seems still broken to me - unless I'm missing something.


git rev-parse HEAD
4641ed8957a7657f9ef2126362a42a06e978a478
poetry build --format wheel

unzip -l dist/isort-5.11.2-py3-none-any.whl | head -10
Archive:  dist/isort-5.11.2-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
    35069  1980-01-01 00:00   CHANGELOG.md
     1089  1980-01-01 00:00   LICENSE
      871  1980-01-01 00:00   isort/__init__.py
       36  1980-01-01 00:00   isort/__main__.py
      310  1980-01-01 00:00   isort/_future/__init__.py
    44114  1980-01-01 00:00   isort/_future/_dataclasses.py
     1072  1980-01-01 00:00   isort/_vendored/tomli/LICENSE

**Comment by staticdev** [comment]
@gene-git sorry, my fault.. I hope it is now fixed on 5.11.4 =)
