### ISSUE TITLE
Inconsistent tag naming

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/isort#2053]
I just noticed that `v5.11.3` is the first (and so far only tag) with a leading `v`. Until `5.11.3` it was just the version itself. Not sure if that was intended. That's a minor issue if you manually update the pre-commit version for `isort`. You just have to know it.

https://github.com/PyCQA/isort/tags

**Comment by timothycrosley** [comment]
Hi! Thanks for the report. This was not intentional and just the result of moving to a fully automated deploy process. We've updated the deploy to use the old versioning tagging to avoid confusion.
