### ISSUE TITLE
pip-shims<=0.3.4

### ISSUE THREAD

**Issue by AtitBimali** [PyCQA/isort#2079]
I am getting "poetry configuration is invalid" when trying to commit my code on GitHub

here is the pre-commit log https://pastebin.com/9mtszQdP

I was able to fix it by removing the `pip-shims<=0.3.4`  by accessing the pre-commit-->isort cache but I don't know how I could do that in GitHub workflow

**Comment by timothycrosley** [comment]
This should be fixed in the latest version of isort
