### ISSUE TITLE
How to fix poetry bug for Python 3.7?

### ISSUE THREAD

**Issue by sijunhe** [PyCQA/isort#2084]
I am aware that bumping isort to `5.12.0` would resolve #2077, but `5.12.0` requires python 3.8+. Any recommendation on how to resolve this bug for using pre-commit and isort in Python 3.7?

**Comment by abravalheri** [comment]
For anyone looking for this, I believe that the fix was introduced in `5.11.5` (which can also be pinned for `pre-commit`).
