### ISSUE TITLE
WARNING: isort 5.12.0 does not provide the extra....

### ISSUE THREAD

**Issue by kad99kev** [PyCQA/isort#2088]
Hello!

I apologise if this issue was already raised, I couldn't find anything on this topic so I decided to raise one myself.

Whenever I try to install the extras - `pipfile_deprecated_finder` and `requirements_deprecated_finder`, I get an warning saying:

```zsh
WARNING: isort 5.12.0 does not provide the extra 'pipfile_deprecated_finder'
WARNING: isort 5.12.0 does not provide the extra 'requirements_deprecated_finder'
```

This doesn't stop installation, however, I get this error later:

```zsh
pkg_resources.UnknownExtra: isort 5.12.0 has no such extra feature 'pipfile_deprecated_finder'
```

Can you please advice on why this might be happening? Thanks!

System info:
- Windows platform
- Ubuntu 22.04.1 LTS on WSL 2
- Miniconda3

**Comment by staticdev** [comment]
Hello @kad99kev, these in fact were removed from latest versions. pyproject.toml has become basically the new standard for python dependencies so removal for a decision to make `isort` maintenance simpler.

**Comment by kad99kev** [comment]
Thanks for this @staticdev!

I am assuming, if there is another library that tries to install it via `isort[requirements_deprecated_finder,pipfile_deprecated_finder]`, then `pkg_resources` would raise an issue? So the advice would be to simple do `pip install isort`?

Thanks once again!

**Comment by staticdev** [comment]
Exactly! `pip install isort` or if you use poetry `poetry add isort`

**Comment by staticdev** [comment]
@kad99kev I would even recommend to replace the files [MANIFEST.in](https://github.com/ugr-sail/sinergym/blob/main/MANIFEST.in), [requirements.txt](https://github.com/ugr-sail/sinergym/blob/main/requirements.txt), [setup.cfg](https://github.com/ugr-sail/sinergym/blob/main/setup.cfg) and [setup.py](https://github.com/ugr-sail/sinergym/blob/main/setup.py) in this project with `pyproject.toml` as recommended by [PEP 517](https://www.python.org/dev/peps/pep-0517/) and [518](https://www.python.org/dev/peps/pep-0518/). This was done in isort project [in 2019](https://github.com/PyCQA/isort/commit/635ecd045994f4f5df0ef1b1854de21f4c9860a0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711).

Some good references:
* https://medium.com/@cjolowicz/hypermodern-python-d44485d9d769
* https://python-poetry.org/docs/pyproject/
