### ISSUE TITLE
SyntaxError when combining `import __future__` and `from __future__ import ...`

### ISSUE THREAD

**Issue by jonathanslenders** [PyCQA/isort#2100]
Consider this input file, which is correct and runs as it should:

```python
from __future__ import annotations
import __future__
```

Run isort over this file. It will turn the imports around:

```python
import __future__
from __future__ import annotations
```

This is a `SyntaxError`:
```
SyntaxError: from __future__ imports must occur at the beginning of the file
```

**Comment by staticdev** [comment]
@jonathanslenders I see this is very edgy-case. Would you mind describing why should a python file have `__future__` imported in these two styles? If I was reviewing a code with both it would immediately trigger an alert to me to understand the reason.

**Comment by jonathanslenders** [comment]
@staticdev: Because we are using `__future__._Feature`:
https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/python_input.py#L436

I don't think there is any other way to write that.

**Comment by staticdev** [comment]
Thanks, it is clear there is a bug. I added the labels and we can close this one as duplicate.
