### ISSUE TITLE
isort merge driver for git etc

### ISSUE THREAD

**Issue by graingert** [PyCQA/isort#712]
Some tool to automatically handle merge conflicts in files. Where the only conflicts are in the imports: Take the imports in 'theirs' and 'ours' and run isort on the union

**Comment by timothycrosley** [comment]
@graingert this sounds awesome! I don't have the bandwidth to work on this at the moment but I would happily review a pull request that added such functionality

~Timothy

**Comment by timothycrosley** [comment]
Since this has been open for over two years without much interest shown, despite my own opinion that it could be cool, I’m going to close it. If anyone has a strong interest in reviving this, please feel empowered to open a new ticket that references this one.

Thanks!

~Timothy
