### ISSUE TITLE
isort messes up pylint tags

### ISSUE THREAD

**Issue by bersbersbers** [PyCQA/isort#758]
This
```
from time import (loong, looong, looonger,  # pylint: disable=E0611
                  looongest, muchlooonger,  # pylint: disable=E0611
                  evenloooooooooooooonger)  # pylint: disable=E0611
```
becomes
```
from time import \
    evenloooooooooooooonger  # pylint: disable=E0611; pylint: disable=E0611; pylint: disable=E0611
from time import loong, looong, looonger, looongest, muchlooonger

```

after `isort`. As a consequence, pylint finds errors it did not find before:

```
C:\Work\Desktop>pylint --disable=R,C,W bug.py & isort bug.py -d > out.py & pylint --disable=R,C,W out.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

************* Module out
out.py:1:0: E0611: No name 'evenloooooooooooooonger' in module 'time' (no-name-in-module)

----------------------------------------------------------------------
Your code has been rated at -15.00/10 (previous run: -15.00/10, +0.00)
```

[bug.py.txt](https://github.com/timothycrosley/isort/files/2464362/bug.py.txt)

**Comment by Alex-Addy** [comment]
I have a similar issue with `isort` moving `pylint` block disables around. So this:
```python
# pylint: disable=no-name-in-module
from third_party import (
   name,
   another_name,
   ...
)
# pylint: enable=no-name-in-module

import first_party
from first_party import ...
```
becomes:
```python
# pylint: disable=no-name-in-module
from third_party import (
   name,
   another_name,
   ...
)

import first_party
from first_party import ...

# pylint: enable=no-name-in-module
```

Expanding the block disable to an undesirable degree.

**Comment by timothycrosley** [comment]
While the issue itself has not been resolved (moving around imports intermixed with comments is tricky) isort now has a better way of turning itself off and on, which could be helpful in cases like this: https://timothycrosley.github.io/isort/docs/configuration/action_comments/#isort-off

**Comment by timothycrosley** [comment]
@Alex-Addy for your example in particular, there is not much isort can do as the comment has no clear association to any import. I would suggest adding a split to make the usage explicit:

```python3
# pylint: disable=no-name-in-module
from third_party import (
   name,
   another_name,
   ...
)
# pylint: enable=no-name-in-module
# isort: split

import first_party
from first_party import ...
```

Alternatively, the [treat_all_comment_as__code](https://pycqa.github.io/isort/docs/configuration/options/#treat-all-comments-as-code) option can be used that does the same automatically for all free floating comments.

**Comment by timothycrosley** [comment]
This appears to be fixed in develop, and now turns the above into:

```
from time import evenloooooooooooooonger  # pylint: disable=E0611
from time import loong, looong, looonger, looongest, muchlooonger  # pylint: disable=E0611
```
which should pass pylint
