### ISSUE TITLE
Group options in the help

### ISSUE THREAD

**Issue by antoine-gallix** [PyCQA/isort#880]
The number of options is already too long to be read in totality quickly when looking for an option in the `isort --help` screen. I think the help display could gain in readability if the commands were grouped by areas. For example `target` for all options related of the choice of files to parse, or `behavior` for options related on what the tool will do on each of the files and `output` for options related on the output format

**Comment by tobiasherp** [comment]
+1
Grouping the options seems to be hard when using `argparse` (which usually simply groups by positional and optional arguments); it was (or, more precisely: **is**) much easier when using `optparse`. This module has been deprecated long ago (a mistake, IMO), but it still exists, and in this regard it is superior.

However, it seems to be possible to do options grouping with `argparse`; `virtualenv` does it (but I didn't find out yet _how_).

**Comment by Bhupesh-V** [comment]
> +1
> Grouping the options seems to be hard when using `argparse` (which usually simply groups by positional and optional arguments); it was (or, more precisely: **is**) much easier when using `optparse`. This module has been deprecated long ago (a mistake, IMO), but it still exists, and in this regard it is superior.
> 
> However, it seems to be possible to do options grouping with `argparse`; `virtualenv` does it (but I didn't find out yet _how_).

I think [`getopt`](https://docs.python.org/3.6/library/getopt.html#module-getopt) can help in this regard

**Comment by infinityxxx** [comment]
@timothycrosley please could you take a look at my hacktober attempt at this issue?
